// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: games.proto

package hr.client.appuser;

@SuppressWarnings("unused")
public final class Games {
  private Games() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetGameListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetGameList)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetGameList}
   */
  public  static final class GetGameList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetGameList)
      GetGameListOrBuilder {
    // Use GetGameList.newBuilder() to construct.
    private GetGameList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetGameList() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetGameList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.Games.GetGameList.class, hr.client.appuser.Games.GetGameList.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.Games.GetGameList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.Games.GetGameList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.GetGameList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.Games.GetGameList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetGameList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetGameList)
        hr.client.appuser.Games.GetGameListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.Games.GetGameList.class, hr.client.appuser.Games.GetGameList.Builder.class);
      }

      // Construct using hr.client.appuser.Games.GetGameList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameList_descriptor;
      }

      public hr.client.appuser.Games.GetGameList getDefaultInstanceForType() {
        return hr.client.appuser.Games.GetGameList.getDefaultInstance();
      }

      public hr.client.appuser.Games.GetGameList build() {
        hr.client.appuser.Games.GetGameList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.Games.GetGameList buildPartial() {
        hr.client.appuser.Games.GetGameList result = new hr.client.appuser.Games.GetGameList(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.Games.GetGameList) {
          return mergeFrom((hr.client.appuser.Games.GetGameList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.Games.GetGameList other) {
        if (other == hr.client.appuser.Games.GetGameList.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.Games.GetGameList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.Games.GetGameList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetGameList)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetGameList)
    private static final hr.client.appuser.Games.GetGameList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.Games.GetGameList();
    }

    public static hr.client.appuser.Games.GetGameList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetGameList>
        PARSER = new com.google.protobuf.AbstractParser<GetGameList>() {
      public GetGameList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetGameList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetGameList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGameList> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.Games.GetGameList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetGameListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetGameListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    int getResultCode();

    /**
     * <code>optional string errorInfo = 2;</code>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    java.util.List<hr.client.appuser.Games.Game> 
        getGameList();
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    hr.client.appuser.Games.Game getGame(int index);
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    int getGameCount();
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    java.util.List<? extends hr.client.appuser.Games.GameOrBuilder> 
        getGameOrBuilderList();
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    hr.client.appuser.Games.GameOrBuilder getGameOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetGameListResponse}
   */
  public  static final class GetGameListResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetGameListResponse)
      GetGameListResponseOrBuilder {
    // Use GetGameListResponse.newBuilder() to construct.
    private GetGameListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetGameListResponse() {
      resultCode_ = 0;
      errorInfo_ = "";
      game_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetGameListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              resultCode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorInfo_ = s;
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                game_ = new java.util.ArrayList<hr.client.appuser.Games.Game>();
                mutable_bitField0_ |= 0x00000004;
              }
              game_.add(input.readMessage(hr.client.appuser.Games.Game.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          game_ = java.util.Collections.unmodifiableList(game_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.Games.GetGameListResponse.class, hr.client.appuser.Games.GetGameListResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int ERRORINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorInfo_;
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GAME_FIELD_NUMBER = 3;
    private java.util.List<hr.client.appuser.Games.Game> game_;
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    public java.util.List<hr.client.appuser.Games.Game> getGameList() {
      return game_;
    }
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    public java.util.List<? extends hr.client.appuser.Games.GameOrBuilder> 
        getGameOrBuilderList() {
      return game_;
    }
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    public int getGameCount() {
      return game_.size();
    }
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    public hr.client.appuser.Games.Game getGame(int index) {
      return game_.get(index);
    }
    /**
     * <code>repeated .hr.client.appuser.Game game = 3;</code>
     */
    public hr.client.appuser.Games.GameOrBuilder getGameOrBuilder(
        int index) {
      return game_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultCode_ != 0) {
        output.writeInt32(1, resultCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, errorInfo_);
      }
      for (int i = 0; i < game_.size(); i++) {
        output.writeMessage(3, game_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errorInfo_);
      }
      for (int i = 0; i < game_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, game_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.GetGameListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.Games.GetGameListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetGameListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetGameListResponse)
        hr.client.appuser.Games.GetGameListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.Games.GetGameListResponse.class, hr.client.appuser.Games.GetGameListResponse.Builder.class);
      }

      // Construct using hr.client.appuser.Games.GetGameListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getGameFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        resultCode_ = 0;

        errorInfo_ = "";

        if (gameBuilder_ == null) {
          game_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          gameBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_GetGameListResponse_descriptor;
      }

      public hr.client.appuser.Games.GetGameListResponse getDefaultInstanceForType() {
        return hr.client.appuser.Games.GetGameListResponse.getDefaultInstance();
      }

      public hr.client.appuser.Games.GetGameListResponse build() {
        hr.client.appuser.Games.GetGameListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.Games.GetGameListResponse buildPartial() {
        hr.client.appuser.Games.GetGameListResponse result = new hr.client.appuser.Games.GetGameListResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.resultCode_ = resultCode_;
        result.errorInfo_ = errorInfo_;
        if (gameBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            game_ = java.util.Collections.unmodifiableList(game_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.game_ = game_;
        } else {
          result.game_ = gameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.Games.GetGameListResponse) {
          return mergeFrom((hr.client.appuser.Games.GetGameListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.Games.GetGameListResponse other) {
        if (other == hr.client.appuser.Games.GetGameListResponse.getDefaultInstance()) return this;
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        if (!other.getErrorInfo().isEmpty()) {
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (gameBuilder_ == null) {
          if (!other.game_.isEmpty()) {
            if (game_.isEmpty()) {
              game_ = other.game_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureGameIsMutable();
              game_.addAll(other.game_);
            }
            onChanged();
          }
        } else {
          if (!other.game_.isEmpty()) {
            if (gameBuilder_.isEmpty()) {
              gameBuilder_.dispose();
              gameBuilder_ = null;
              game_ = other.game_;
              bitField0_ = (bitField0_ & ~0x00000004);
              gameBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getGameFieldBuilder() : null;
            } else {
              gameBuilder_.addAllMessages(other.game_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.Games.GetGameListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.Games.GetGameListResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int resultCode_ ;
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder clearErrorInfo() {
        
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private java.util.List<hr.client.appuser.Games.Game> game_ =
        java.util.Collections.emptyList();
      private void ensureGameIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          game_ = new java.util.ArrayList<hr.client.appuser.Games.Game>(game_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          hr.client.appuser.Games.Game, hr.client.appuser.Games.Game.Builder, hr.client.appuser.Games.GameOrBuilder> gameBuilder_;

      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public java.util.List<hr.client.appuser.Games.Game> getGameList() {
        if (gameBuilder_ == null) {
          return java.util.Collections.unmodifiableList(game_);
        } else {
          return gameBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public int getGameCount() {
        if (gameBuilder_ == null) {
          return game_.size();
        } else {
          return gameBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public hr.client.appuser.Games.Game getGame(int index) {
        if (gameBuilder_ == null) {
          return game_.get(index);
        } else {
          return gameBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder setGame(
          int index, hr.client.appuser.Games.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameIsMutable();
          game_.set(index, value);
          onChanged();
        } else {
          gameBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder setGame(
          int index, hr.client.appuser.Games.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          ensureGameIsMutable();
          game_.set(index, builderForValue.build());
          onChanged();
        } else {
          gameBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder addGame(hr.client.appuser.Games.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameIsMutable();
          game_.add(value);
          onChanged();
        } else {
          gameBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder addGame(
          int index, hr.client.appuser.Games.Game value) {
        if (gameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGameIsMutable();
          game_.add(index, value);
          onChanged();
        } else {
          gameBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder addGame(
          hr.client.appuser.Games.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          ensureGameIsMutable();
          game_.add(builderForValue.build());
          onChanged();
        } else {
          gameBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder addGame(
          int index, hr.client.appuser.Games.Game.Builder builderForValue) {
        if (gameBuilder_ == null) {
          ensureGameIsMutable();
          game_.add(index, builderForValue.build());
          onChanged();
        } else {
          gameBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder addAllGame(
          java.lang.Iterable<? extends hr.client.appuser.Games.Game> values) {
        if (gameBuilder_ == null) {
          ensureGameIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, game_);
          onChanged();
        } else {
          gameBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder clearGame() {
        if (gameBuilder_ == null) {
          game_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          gameBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public Builder removeGame(int index) {
        if (gameBuilder_ == null) {
          ensureGameIsMutable();
          game_.remove(index);
          onChanged();
        } else {
          gameBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public hr.client.appuser.Games.Game.Builder getGameBuilder(
          int index) {
        return getGameFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public hr.client.appuser.Games.GameOrBuilder getGameOrBuilder(
          int index) {
        if (gameBuilder_ == null) {
          return game_.get(index);  } else {
          return gameBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public java.util.List<? extends hr.client.appuser.Games.GameOrBuilder> 
           getGameOrBuilderList() {
        if (gameBuilder_ != null) {
          return gameBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(game_);
        }
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public hr.client.appuser.Games.Game.Builder addGameBuilder() {
        return getGameFieldBuilder().addBuilder(
            hr.client.appuser.Games.Game.getDefaultInstance());
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public hr.client.appuser.Games.Game.Builder addGameBuilder(
          int index) {
        return getGameFieldBuilder().addBuilder(
            index, hr.client.appuser.Games.Game.getDefaultInstance());
      }
      /**
       * <code>repeated .hr.client.appuser.Game game = 3;</code>
       */
      public java.util.List<hr.client.appuser.Games.Game.Builder> 
           getGameBuilderList() {
        return getGameFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          hr.client.appuser.Games.Game, hr.client.appuser.Games.Game.Builder, hr.client.appuser.Games.GameOrBuilder> 
          getGameFieldBuilder() {
        if (gameBuilder_ == null) {
          gameBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              hr.client.appuser.Games.Game, hr.client.appuser.Games.Game.Builder, hr.client.appuser.Games.GameOrBuilder>(
                  game_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          game_ = null;
        }
        return gameBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetGameListResponse)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetGameListResponse)
    private static final hr.client.appuser.Games.GetGameListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.Games.GetGameListResponse();
    }

    public static hr.client.appuser.Games.GetGameListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetGameListResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetGameListResponse>() {
      public GetGameListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetGameListResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetGameListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGameListResponse> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.Games.GetGameListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.Game)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 sequenceNum = 1;</code>
     */
    int getSequenceNum();

    /**
     * <code>optional string gameId = 2;</code>
     */
    java.lang.String getGameId();
    /**
     * <code>optional string gameId = 2;</code>
     */
    com.google.protobuf.ByteString
        getGameIdBytes();

    /**
     * <code>optional string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>optional string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>optional string description = 4;</code>
     */
    java.lang.String getDescription();
    /**
     * <code>optional string description = 4;</code>
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>optional string iconUrl = 5;</code>
     */
    java.lang.String getIconUrl();
    /**
     * <code>optional string iconUrl = 5;</code>
     */
    com.google.protobuf.ByteString
        getIconUrlBytes();

    /**
     * <code>optional string packageUrl = 6;</code>
     */
    java.lang.String getPackageUrl();
    /**
     * <code>optional string packageUrl = 6;</code>
     */
    com.google.protobuf.ByteString
        getPackageUrlBytes();

    /**
     * <code>map&lt;string, string&gt; appClientParas = 7;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAppClientParas();
  }
  /**
   * Protobuf type {@code hr.client.appuser.Game}
   */
  public  static final class Game extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.Game)
      GameOrBuilder {
    // Use Game.newBuilder() to construct.
    private Game(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Game() {
      sequenceNum_ = 0;
      gameId_ = "";
      name_ = "";
      description_ = "";
      iconUrl_ = "";
      packageUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Game(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              sequenceNum_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              gameId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              description_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              iconUrl_ = s;
              break;
            }
            case 50: {
              String s = input.readStringRequireUtf8();

              packageUrl_ = s;
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                appClientParas_ = com.google.protobuf.MapField.newMapField(
                    AppClientParasDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000040;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              appClientParas = input.readMessage(
                  AppClientParasDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              appClientParas_.getMutableMap().put(appClientParas.getKey(), appClientParas.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_Game_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 7:
          return internalGetAppClientParas();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.Games.internal_static_hr_client_appuser_Game_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.Games.Game.class, hr.client.appuser.Games.Game.Builder.class);
    }

    private int bitField0_;
    public static final int SEQUENCENUM_FIELD_NUMBER = 1;
    private int sequenceNum_;
    /**
     * <code>optional int32 sequenceNum = 1;</code>
     */
    public int getSequenceNum() {
      return sequenceNum_;
    }

    public static final int GAMEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object gameId_;
    /**
     * <code>optional string gameId = 2;</code>
     */
    public java.lang.String getGameId() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gameId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string gameId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getGameIdBytes() {
      java.lang.Object ref = gameId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gameId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>optional string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>optional string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 4;
    private volatile java.lang.Object description_;
    /**
     * <code>optional string description = 4;</code>
     */
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>optional string description = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICONURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object iconUrl_;
    /**
     * <code>optional string iconUrl = 5;</code>
     */
    public java.lang.String getIconUrl() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iconUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string iconUrl = 5;</code>
     */
    public com.google.protobuf.ByteString
        getIconUrlBytes() {
      java.lang.Object ref = iconUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iconUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PACKAGEURL_FIELD_NUMBER = 6;
    private volatile java.lang.Object packageUrl_;
    /**
     * <code>optional string packageUrl = 6;</code>
     */
    public java.lang.String getPackageUrl() {
      java.lang.Object ref = packageUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        packageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string packageUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getPackageUrlBytes() {
      java.lang.Object ref = packageUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        packageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int APPCLIENTPARAS_FIELD_NUMBER = 7;
    private static final class AppClientParasDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  hr.client.appuser.Games.internal_static_hr_client_appuser_Game_AppClientParasEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> appClientParas_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAppClientParas() {
      if (appClientParas_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AppClientParasDefaultEntryHolder.defaultEntry);
     }
      return appClientParas_;
    }
    /**
     * <code>map&lt;string, string&gt; appClientParas = 7;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getAppClientParas() {
      return internalGetAppClientParas().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sequenceNum_ != 0) {
        output.writeInt32(1, sequenceNum_);
      }
      if (!getGameIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, gameId_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, description_);
      }
      if (!getIconUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, iconUrl_);
      }
      if (!getPackageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, packageUrl_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAppClientParas().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        appClientParas = AppClientParasDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(7, appClientParas);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sequenceNum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sequenceNum_);
      }
      if (!getGameIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, gameId_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, name_);
      }
      if (!getDescriptionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, description_);
      }
      if (!getIconUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, iconUrl_);
      }
      if (!getPackageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, packageUrl_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAppClientParas().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        appClientParas = AppClientParasDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(7, appClientParas);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.Games.Game parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.Game parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.Game parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.Games.Game parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.Games.Game parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.Game parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.Game parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.Games.Game parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.Games.Game parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.Games.Game parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.Games.Game prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.Game}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.Game)
        hr.client.appuser.Games.GameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_Game_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetAppClientParas();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 7:
            return internalGetMutableAppClientParas();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_Game_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.Games.Game.class, hr.client.appuser.Games.Game.Builder.class);
      }

      // Construct using hr.client.appuser.Games.Game.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sequenceNum_ = 0;

        gameId_ = "";

        name_ = "";

        description_ = "";

        iconUrl_ = "";

        packageUrl_ = "";

        internalGetMutableAppClientParas().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.Games.internal_static_hr_client_appuser_Game_descriptor;
      }

      public hr.client.appuser.Games.Game getDefaultInstanceForType() {
        return hr.client.appuser.Games.Game.getDefaultInstance();
      }

      public hr.client.appuser.Games.Game build() {
        hr.client.appuser.Games.Game result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.Games.Game buildPartial() {
        hr.client.appuser.Games.Game result = new hr.client.appuser.Games.Game(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.sequenceNum_ = sequenceNum_;
        result.gameId_ = gameId_;
        result.name_ = name_;
        result.description_ = description_;
        result.iconUrl_ = iconUrl_;
        result.packageUrl_ = packageUrl_;
        result.appClientParas_ = internalGetAppClientParas();
        result.appClientParas_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.Games.Game) {
          return mergeFrom((hr.client.appuser.Games.Game)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.Games.Game other) {
        if (other == hr.client.appuser.Games.Game.getDefaultInstance()) return this;
        if (other.getSequenceNum() != 0) {
          setSequenceNum(other.getSequenceNum());
        }
        if (!other.getGameId().isEmpty()) {
          gameId_ = other.gameId_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          onChanged();
        }
        if (!other.getIconUrl().isEmpty()) {
          iconUrl_ = other.iconUrl_;
          onChanged();
        }
        if (!other.getPackageUrl().isEmpty()) {
          packageUrl_ = other.packageUrl_;
          onChanged();
        }
        internalGetMutableAppClientParas().mergeFrom(
            other.internalGetAppClientParas());
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.Games.Game parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.Games.Game) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int sequenceNum_ ;
      /**
       * <code>optional int32 sequenceNum = 1;</code>
       */
      public int getSequenceNum() {
        return sequenceNum_;
      }
      /**
       * <code>optional int32 sequenceNum = 1;</code>
       */
      public Builder setSequenceNum(int value) {
        
        sequenceNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 sequenceNum = 1;</code>
       */
      public Builder clearSequenceNum() {
        
        sequenceNum_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object gameId_ = "";
      /**
       * <code>optional string gameId = 2;</code>
       */
      public java.lang.String getGameId() {
        java.lang.Object ref = gameId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gameId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string gameId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getGameIdBytes() {
        java.lang.Object ref = gameId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gameId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string gameId = 2;</code>
       */
      public Builder setGameId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        gameId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameId = 2;</code>
       */
      public Builder clearGameId() {
        
        gameId_ = getDefaultInstance().getGameId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string gameId = 2;</code>
       */
      public Builder setGameIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        gameId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>optional string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>optional string description = 4;</code>
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        description_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder clearDescription() {
        
        description_ = getDefaultInstance().getDescription();
        onChanged();
        return this;
      }
      /**
       * <code>optional string description = 4;</code>
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        description_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iconUrl_ = "";
      /**
       * <code>optional string iconUrl = 5;</code>
       */
      public java.lang.String getIconUrl() {
        java.lang.Object ref = iconUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iconUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string iconUrl = 5;</code>
       */
      public com.google.protobuf.ByteString
          getIconUrlBytes() {
        java.lang.Object ref = iconUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iconUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string iconUrl = 5;</code>
       */
      public Builder setIconUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iconUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string iconUrl = 5;</code>
       */
      public Builder clearIconUrl() {
        
        iconUrl_ = getDefaultInstance().getIconUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string iconUrl = 5;</code>
       */
      public Builder setIconUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iconUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object packageUrl_ = "";
      /**
       * <code>optional string packageUrl = 6;</code>
       */
      public java.lang.String getPackageUrl() {
        java.lang.Object ref = packageUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          packageUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string packageUrl = 6;</code>
       */
      public com.google.protobuf.ByteString
          getPackageUrlBytes() {
        java.lang.Object ref = packageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          packageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string packageUrl = 6;</code>
       */
      public Builder setPackageUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        packageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageUrl = 6;</code>
       */
      public Builder clearPackageUrl() {
        
        packageUrl_ = getDefaultInstance().getPackageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string packageUrl = 6;</code>
       */
      public Builder setPackageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        packageUrl_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> appClientParas_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetAppClientParas() {
        if (appClientParas_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AppClientParasDefaultEntryHolder.defaultEntry);
       }
        return appClientParas_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableAppClientParas() {
        onChanged();;
        if (appClientParas_ == null) {
          appClientParas_ = com.google.protobuf.MapField.newMapField(
              AppClientParasDefaultEntryHolder.defaultEntry);
        }
        if (!appClientParas_.isMutable()) {
          appClientParas_ = appClientParas_.copy();
        }
        return appClientParas_;
      }
      /**
       * <code>map&lt;string, string&gt; appClientParas = 7;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getAppClientParas() {
        return internalGetAppClientParas().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; appClientParas = 7;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableAppClientParas() {
        return internalGetMutableAppClientParas().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; appClientParas = 7;</code>
       */
      public Builder putAllAppClientParas(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableAppClientParas().putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.Game)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.Game)
    private static final hr.client.appuser.Games.Game DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.Games.Game();
    }

    public static hr.client.appuser.Games.Game getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Game>
        PARSER = new com.google.protobuf.AbstractParser<Game>() {
      public Game parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Game(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Game> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Game> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.Games.Game getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetGameList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetGameList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetGameListResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetGameListResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_Game_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_Game_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_Game_AppClientParasEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_Game_AppClientParasEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013games.proto\022\021hr.client.appuser\"\r\n\013GetG" +
      "ameList\"c\n\023GetGameListResponse\022\022\n\nresult" +
      "Code\030\001 \001(\005\022\021\n\terrorInfo\030\002 \001(\t\022%\n\004game\030\003 " +
      "\003(\0132\027.hr.client.appuser.Game\"\357\001\n\004Game\022\023\n" +
      "\013sequenceNum\030\001 \001(\005\022\016\n\006gameId\030\002 \001(\t\022\014\n\004na" +
      "me\030\003 \001(\t\022\023\n\013description\030\004 \001(\t\022\017\n\007iconUrl" +
      "\030\005 \001(\t\022\022\n\npackageUrl\030\006 \001(\t\022C\n\016appClientP" +
      "aras\030\007 \003(\0132+.hr.client.appuser.Game.AppC" +
      "lientParasEntry\0325\n\023AppClientParasEntry\022\013" +
      "\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hr_client_appuser_GetGameList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_client_appuser_GetGameList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetGameList_descriptor,
        new java.lang.String[] { });
    internal_static_hr_client_appuser_GetGameListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hr_client_appuser_GetGameListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetGameListResponse_descriptor,
        new java.lang.String[] { "ResultCode", "ErrorInfo", "Game", });
    internal_static_hr_client_appuser_Game_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hr_client_appuser_Game_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_Game_descriptor,
        new java.lang.String[] { "SequenceNum", "GameId", "Name", "Description", "IconUrl", "PackageUrl", "AppClientParas", });
    internal_static_hr_client_appuser_Game_AppClientParasEntry_descriptor =
      internal_static_hr_client_appuser_Game_descriptor.getNestedTypes().get(0);
    internal_static_hr_client_appuser_Game_AppClientParasEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_Game_AppClientParasEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
