// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getUserInfo.proto

package hr.client.appuser;

@SuppressWarnings("unused")
public final class GetUserInfo {
  private GetUserInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetUserDetailOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetUserDetail)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetUserDetail}
   */
  public  static final class GetUserDetail extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetUserDetail)
      GetUserDetailOrBuilder {
    // Use GetUserDetail.newBuilder() to construct.
    private GetUserDetail(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetUserDetail() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetUserDetail(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetail_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetail_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.GetUserInfo.GetUserDetail.class, hr.client.appuser.GetUserInfo.GetUserDetail.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetail parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.GetUserInfo.GetUserDetail prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetUserDetail}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetUserDetail)
        hr.client.appuser.GetUserInfo.GetUserDetailOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetail_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetail_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.GetUserInfo.GetUserDetail.class, hr.client.appuser.GetUserInfo.GetUserDetail.Builder.class);
      }

      // Construct using hr.client.appuser.GetUserInfo.GetUserDetail.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetail_descriptor;
      }

      public hr.client.appuser.GetUserInfo.GetUserDetail getDefaultInstanceForType() {
        return hr.client.appuser.GetUserInfo.GetUserDetail.getDefaultInstance();
      }

      public hr.client.appuser.GetUserInfo.GetUserDetail build() {
        hr.client.appuser.GetUserInfo.GetUserDetail result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.GetUserInfo.GetUserDetail buildPartial() {
        hr.client.appuser.GetUserInfo.GetUserDetail result = new hr.client.appuser.GetUserInfo.GetUserDetail(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.GetUserInfo.GetUserDetail) {
          return mergeFrom((hr.client.appuser.GetUserInfo.GetUserDetail)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.GetUserInfo.GetUserDetail other) {
        if (other == hr.client.appuser.GetUserInfo.GetUserDetail.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.GetUserInfo.GetUserDetail parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.GetUserInfo.GetUserDetail) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetUserDetail)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetUserDetail)
    private static final hr.client.appuser.GetUserInfo.GetUserDetail DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.GetUserInfo.GetUserDetail();
    }

    public static hr.client.appuser.GetUserInfo.GetUserDetail getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserDetail>
        PARSER = new com.google.protobuf.AbstractParser<GetUserDetail>() {
      public GetUserDetail parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetUserDetail(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetUserDetail> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserDetail> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.GetUserInfo.GetUserDetail getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetUserDetailResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetUserDetailResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    int getResultCode();

    /**
     * <code>optional string errorInfo = 2;</code>
     */
    java.lang.String getErrorInfo();
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    com.google.protobuf.ByteString
        getErrorInfoBytes();

    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    boolean hasUserInfo();
    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    hr.client.appuser.UserInfoOuterClass.UserInfo getUserInfo();
    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder();
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetUserDetailResponse}
   */
  public  static final class GetUserDetailResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetUserDetailResponse)
      GetUserDetailResponseOrBuilder {
    // Use GetUserDetailResponse.newBuilder() to construct.
    private GetUserDetailResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetUserDetailResponse() {
      resultCode_ = 0;
      errorInfo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetUserDetailResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              resultCode_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              errorInfo_ = s;
              break;
            }
            case 26: {
              hr.client.appuser.UserInfoOuterClass.UserInfo.Builder subBuilder = null;
              if (userInfo_ != null) {
                subBuilder = userInfo_.toBuilder();
              }
              userInfo_ = input.readMessage(hr.client.appuser.UserInfoOuterClass.UserInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(userInfo_);
                userInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetailResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetailResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.GetUserInfo.GetUserDetailResponse.class, hr.client.appuser.GetUserInfo.GetUserDetailResponse.Builder.class);
    }

    public static final int RESULTCODE_FIELD_NUMBER = 1;
    private int resultCode_;
    /**
     * <code>optional int32 resultCode = 1;</code>
     */
    public int getResultCode() {
      return resultCode_;
    }

    public static final int ERRORINFO_FIELD_NUMBER = 2;
    private volatile java.lang.Object errorInfo_;
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    public java.lang.String getErrorInfo() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorInfo_ = s;
        return s;
      }
    }
    /**
     * <code>optional string errorInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getErrorInfoBytes() {
      java.lang.Object ref = errorInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERINFO_FIELD_NUMBER = 3;
    private hr.client.appuser.UserInfoOuterClass.UserInfo userInfo_;
    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    public boolean hasUserInfo() {
      return userInfo_ != null;
    }
    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    public hr.client.appuser.UserInfoOuterClass.UserInfo getUserInfo() {
      return userInfo_ == null ? hr.client.appuser.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
    }
    /**
     * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
     */
    public hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
      return getUserInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultCode_ != 0) {
        output.writeInt32(1, resultCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, errorInfo_);
      }
      if (userInfo_ != null) {
        output.writeMessage(3, getUserInfo());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resultCode_);
      }
      if (!getErrorInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, errorInfo_);
      }
      if (userInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getUserInfo());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.GetUserInfo.GetUserDetailResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetUserDetailResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetUserDetailResponse)
        hr.client.appuser.GetUserInfo.GetUserDetailResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetailResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetailResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.GetUserInfo.GetUserDetailResponse.class, hr.client.appuser.GetUserInfo.GetUserDetailResponse.Builder.class);
      }

      // Construct using hr.client.appuser.GetUserInfo.GetUserDetailResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resultCode_ = 0;

        errorInfo_ = "";

        if (userInfoBuilder_ == null) {
          userInfo_ = null;
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.GetUserInfo.internal_static_hr_client_appuser_GetUserDetailResponse_descriptor;
      }

      public hr.client.appuser.GetUserInfo.GetUserDetailResponse getDefaultInstanceForType() {
        return hr.client.appuser.GetUserInfo.GetUserDetailResponse.getDefaultInstance();
      }

      public hr.client.appuser.GetUserInfo.GetUserDetailResponse build() {
        hr.client.appuser.GetUserInfo.GetUserDetailResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.GetUserInfo.GetUserDetailResponse buildPartial() {
        hr.client.appuser.GetUserInfo.GetUserDetailResponse result = new hr.client.appuser.GetUserInfo.GetUserDetailResponse(this);
        result.resultCode_ = resultCode_;
        result.errorInfo_ = errorInfo_;
        if (userInfoBuilder_ == null) {
          result.userInfo_ = userInfo_;
        } else {
          result.userInfo_ = userInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.GetUserInfo.GetUserDetailResponse) {
          return mergeFrom((hr.client.appuser.GetUserInfo.GetUserDetailResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.GetUserInfo.GetUserDetailResponse other) {
        if (other == hr.client.appuser.GetUserInfo.GetUserDetailResponse.getDefaultInstance()) return this;
        if (other.getResultCode() != 0) {
          setResultCode(other.getResultCode());
        }
        if (!other.getErrorInfo().isEmpty()) {
          errorInfo_ = other.errorInfo_;
          onChanged();
        }
        if (other.hasUserInfo()) {
          mergeUserInfo(other.getUserInfo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.GetUserInfo.GetUserDetailResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.GetUserInfo.GetUserDetailResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resultCode_ ;
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public int getResultCode() {
        return resultCode_;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder setResultCode(int value) {
        
        resultCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 resultCode = 1;</code>
       */
      public Builder clearResultCode() {
        
        resultCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorInfo_ = "";
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public java.lang.String getErrorInfo() {
        java.lang.Object ref = errorInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public com.google.protobuf.ByteString
          getErrorInfoBytes() {
        java.lang.Object ref = errorInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder setErrorInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder clearErrorInfo() {
        
        errorInfo_ = getDefaultInstance().getErrorInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string errorInfo = 2;</code>
       */
      public Builder setErrorInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorInfo_ = value;
        onChanged();
        return this;
      }

      private hr.client.appuser.UserInfoOuterClass.UserInfo userInfo_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          hr.client.appuser.UserInfoOuterClass.UserInfo, hr.client.appuser.UserInfoOuterClass.UserInfo.Builder, hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder> userInfoBuilder_;
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public boolean hasUserInfo() {
        return userInfoBuilder_ != null || userInfo_ != null;
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public hr.client.appuser.UserInfoOuterClass.UserInfo getUserInfo() {
        if (userInfoBuilder_ == null) {
          return userInfo_ == null ? hr.client.appuser.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        } else {
          return userInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public Builder setUserInfo(hr.client.appuser.UserInfoOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          userInfo_ = value;
          onChanged();
        } else {
          userInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public Builder setUserInfo(
          hr.client.appuser.UserInfoOuterClass.UserInfo.Builder builderForValue) {
        if (userInfoBuilder_ == null) {
          userInfo_ = builderForValue.build();
          onChanged();
        } else {
          userInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public Builder mergeUserInfo(hr.client.appuser.UserInfoOuterClass.UserInfo value) {
        if (userInfoBuilder_ == null) {
          if (userInfo_ != null) {
            userInfo_ =
              hr.client.appuser.UserInfoOuterClass.UserInfo.newBuilder(userInfo_).mergeFrom(value).buildPartial();
          } else {
            userInfo_ = value;
          }
          onChanged();
        } else {
          userInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public Builder clearUserInfo() {
        if (userInfoBuilder_ == null) {
          userInfo_ = null;
          onChanged();
        } else {
          userInfo_ = null;
          userInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public hr.client.appuser.UserInfoOuterClass.UserInfo.Builder getUserInfoBuilder() {
        
        onChanged();
        return getUserInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      public hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder getUserInfoOrBuilder() {
        if (userInfoBuilder_ != null) {
          return userInfoBuilder_.getMessageOrBuilder();
        } else {
          return userInfo_ == null ?
              hr.client.appuser.UserInfoOuterClass.UserInfo.getDefaultInstance() : userInfo_;
        }
      }
      /**
       * <code>optional .hr.client.appuser.UserInfo userInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          hr.client.appuser.UserInfoOuterClass.UserInfo, hr.client.appuser.UserInfoOuterClass.UserInfo.Builder, hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder> 
          getUserInfoFieldBuilder() {
        if (userInfoBuilder_ == null) {
          userInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              hr.client.appuser.UserInfoOuterClass.UserInfo, hr.client.appuser.UserInfoOuterClass.UserInfo.Builder, hr.client.appuser.UserInfoOuterClass.UserInfoOrBuilder>(
                  getUserInfo(),
                  getParentForChildren(),
                  isClean());
          userInfo_ = null;
        }
        return userInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetUserDetailResponse)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetUserDetailResponse)
    private static final hr.client.appuser.GetUserInfo.GetUserDetailResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.GetUserInfo.GetUserDetailResponse();
    }

    public static hr.client.appuser.GetUserInfo.GetUserDetailResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetUserDetailResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetUserDetailResponse>() {
      public GetUserDetailResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetUserDetailResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetUserDetailResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetUserDetailResponse> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.GetUserInfo.GetUserDetailResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetUserDetail_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetUserDetail_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetUserDetailResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetUserDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021getUserInfo.proto\022\021hr.client.appuser\032\016" +
      "userInfo.proto\"\017\n\rGetUserDetail\"m\n\025GetUs" +
      "erDetailResponse\022\022\n\nresultCode\030\001 \001(\005\022\021\n\t" +
      "errorInfo\030\002 \001(\t\022-\n\010userInfo\030\003 \001(\0132\033.hr.c" +
      "lient.appuser.UserInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          hr.client.appuser.UserInfoOuterClass.getDescriptor(),
        }, assigner);
    internal_static_hr_client_appuser_GetUserDetail_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_client_appuser_GetUserDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetUserDetail_descriptor,
        new java.lang.String[] { });
    internal_static_hr_client_appuser_GetUserDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hr_client_appuser_GetUserDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetUserDetailResponse_descriptor,
        new java.lang.String[] { "ResultCode", "ErrorInfo", "UserInfo", });
    hr.client.appuser.UserInfoOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
