// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: globalConfig.proto

package hr.client.appuser;

@SuppressWarnings("unused")
public final class GlobalConfig {
  private GlobalConfig() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GetGlobalConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetGlobalConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string appVersion = 1;</code>
     */
    java.lang.String getAppVersion();
    /**
     * <code>optional string appVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppVersionBytes();
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetGlobalConfig}
   */
  public  static final class GetGlobalConfig extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetGlobalConfig)
      GetGlobalConfigOrBuilder {
    // Use GetGlobalConfig.newBuilder() to construct.
    private GetGlobalConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetGlobalConfig() {
      appVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetGlobalConfig(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              appVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfig_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.GlobalConfig.GetGlobalConfig.class, hr.client.appuser.GlobalConfig.GetGlobalConfig.Builder.class);
    }

    public static final int APPVERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object appVersion_;
    /**
     * <code>optional string appVersion = 1;</code>
     */
    public java.lang.String getAppVersion() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string appVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppVersionBytes() {
      java.lang.Object ref = appVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, appVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, appVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.GlobalConfig.GetGlobalConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetGlobalConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetGlobalConfig)
        hr.client.appuser.GlobalConfig.GetGlobalConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfig_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.GlobalConfig.GetGlobalConfig.class, hr.client.appuser.GlobalConfig.GetGlobalConfig.Builder.class);
      }

      // Construct using hr.client.appuser.GlobalConfig.GetGlobalConfig.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfig_descriptor;
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfig getDefaultInstanceForType() {
        return hr.client.appuser.GlobalConfig.GetGlobalConfig.getDefaultInstance();
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfig build() {
        hr.client.appuser.GlobalConfig.GetGlobalConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfig buildPartial() {
        hr.client.appuser.GlobalConfig.GetGlobalConfig result = new hr.client.appuser.GlobalConfig.GetGlobalConfig(this);
        result.appVersion_ = appVersion_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.GlobalConfig.GetGlobalConfig) {
          return mergeFrom((hr.client.appuser.GlobalConfig.GetGlobalConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.GlobalConfig.GetGlobalConfig other) {
        if (other == hr.client.appuser.GlobalConfig.GetGlobalConfig.getDefaultInstance()) return this;
        if (!other.getAppVersion().isEmpty()) {
          appVersion_ = other.appVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.GlobalConfig.GetGlobalConfig parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.GlobalConfig.GetGlobalConfig) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appVersion_ = "";
      /**
       * <code>optional string appVersion = 1;</code>
       */
      public java.lang.String getAppVersion() {
        java.lang.Object ref = appVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string appVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppVersionBytes() {
        java.lang.Object ref = appVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string appVersion = 1;</code>
       */
      public Builder setAppVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string appVersion = 1;</code>
       */
      public Builder clearAppVersion() {
        
        appVersion_ = getDefaultInstance().getAppVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string appVersion = 1;</code>
       */
      public Builder setAppVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetGlobalConfig)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetGlobalConfig)
    private static final hr.client.appuser.GlobalConfig.GetGlobalConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.GlobalConfig.GetGlobalConfig();
    }

    public static hr.client.appuser.GlobalConfig.GetGlobalConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetGlobalConfig>
        PARSER = new com.google.protobuf.AbstractParser<GetGlobalConfig>() {
      public GetGlobalConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetGlobalConfig(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetGlobalConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGlobalConfig> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.GlobalConfig.GetGlobalConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetGlobalConfigResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.GetGlobalConfigResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string interfaceVersion = 1;</code>
     */
    java.lang.String getInterfaceVersion();
    /**
     * <code>optional string interfaceVersion = 1;</code>
     */
    com.google.protobuf.ByteString
        getInterfaceVersionBytes();

    /**
     * <code>optional string couponUrl = 2;</code>
     */
    java.lang.String getCouponUrl();
    /**
     * <code>optional string couponUrl = 2;</code>
     */
    com.google.protobuf.ByteString
        getCouponUrlBytes();

    /**
     * <code>optional string taskUrl = 3;</code>
     */
    java.lang.String getTaskUrl();
    /**
     * <code>optional string taskUrl = 3;</code>
     */
    com.google.protobuf.ByteString
        getTaskUrlBytes();

    /**
     * <code>optional string baseUrl = 4;</code>
     */
    java.lang.String getBaseUrl();
    /**
     * <code>optional string baseUrl = 4;</code>
     */
    com.google.protobuf.ByteString
        getBaseUrlBytes();
  }
  /**
   * Protobuf type {@code hr.client.appuser.GetGlobalConfigResponse}
   */
  public  static final class GetGlobalConfigResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.GetGlobalConfigResponse)
      GetGlobalConfigResponseOrBuilder {
    // Use GetGlobalConfigResponse.newBuilder() to construct.
    private GetGlobalConfigResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetGlobalConfigResponse() {
      interfaceVersion_ = "";
      couponUrl_ = "";
      taskUrl_ = "";
      baseUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetGlobalConfigResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              interfaceVersion_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              couponUrl_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              taskUrl_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              baseUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfigResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.class, hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.Builder.class);
    }

    public static final int INTERFACEVERSION_FIELD_NUMBER = 1;
    private volatile java.lang.Object interfaceVersion_;
    /**
     * <code>optional string interfaceVersion = 1;</code>
     */
    public java.lang.String getInterfaceVersion() {
      java.lang.Object ref = interfaceVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string interfaceVersion = 1;</code>
     */
    public com.google.protobuf.ByteString
        getInterfaceVersionBytes() {
      java.lang.Object ref = interfaceVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COUPONURL_FIELD_NUMBER = 2;
    private volatile java.lang.Object couponUrl_;
    /**
     * <code>optional string couponUrl = 2;</code>
     */
    public java.lang.String getCouponUrl() {
      java.lang.Object ref = couponUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        couponUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string couponUrl = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCouponUrlBytes() {
      java.lang.Object ref = couponUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        couponUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TASKURL_FIELD_NUMBER = 3;
    private volatile java.lang.Object taskUrl_;
    /**
     * <code>optional string taskUrl = 3;</code>
     */
    public java.lang.String getTaskUrl() {
      java.lang.Object ref = taskUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        taskUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string taskUrl = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTaskUrlBytes() {
      java.lang.Object ref = taskUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BASEURL_FIELD_NUMBER = 4;
    private volatile java.lang.Object baseUrl_;
    /**
     * <code>optional string baseUrl = 4;</code>
     */
    public java.lang.String getBaseUrl() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        baseUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string baseUrl = 4;</code>
     */
    public com.google.protobuf.ByteString
        getBaseUrlBytes() {
      java.lang.Object ref = baseUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        baseUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getInterfaceVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, interfaceVersion_);
      }
      if (!getCouponUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, couponUrl_);
      }
      if (!getTaskUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, taskUrl_);
      }
      if (!getBaseUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, baseUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getInterfaceVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, interfaceVersion_);
      }
      if (!getCouponUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, couponUrl_);
      }
      if (!getTaskUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, taskUrl_);
      }
      if (!getBaseUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, baseUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.GlobalConfig.GetGlobalConfigResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.GetGlobalConfigResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.GetGlobalConfigResponse)
        hr.client.appuser.GlobalConfig.GetGlobalConfigResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfigResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.class, hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.Builder.class);
      }

      // Construct using hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        interfaceVersion_ = "";

        couponUrl_ = "";

        taskUrl_ = "";

        baseUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.GlobalConfig.internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor;
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfigResponse getDefaultInstanceForType() {
        return hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.getDefaultInstance();
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfigResponse build() {
        hr.client.appuser.GlobalConfig.GetGlobalConfigResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.GlobalConfig.GetGlobalConfigResponse buildPartial() {
        hr.client.appuser.GlobalConfig.GetGlobalConfigResponse result = new hr.client.appuser.GlobalConfig.GetGlobalConfigResponse(this);
        result.interfaceVersion_ = interfaceVersion_;
        result.couponUrl_ = couponUrl_;
        result.taskUrl_ = taskUrl_;
        result.baseUrl_ = baseUrl_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.GlobalConfig.GetGlobalConfigResponse) {
          return mergeFrom((hr.client.appuser.GlobalConfig.GetGlobalConfigResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.GlobalConfig.GetGlobalConfigResponse other) {
        if (other == hr.client.appuser.GlobalConfig.GetGlobalConfigResponse.getDefaultInstance()) return this;
        if (!other.getInterfaceVersion().isEmpty()) {
          interfaceVersion_ = other.interfaceVersion_;
          onChanged();
        }
        if (!other.getCouponUrl().isEmpty()) {
          couponUrl_ = other.couponUrl_;
          onChanged();
        }
        if (!other.getTaskUrl().isEmpty()) {
          taskUrl_ = other.taskUrl_;
          onChanged();
        }
        if (!other.getBaseUrl().isEmpty()) {
          baseUrl_ = other.baseUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.GlobalConfig.GetGlobalConfigResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.GlobalConfig.GetGlobalConfigResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object interfaceVersion_ = "";
      /**
       * <code>optional string interfaceVersion = 1;</code>
       */
      public java.lang.String getInterfaceVersion() {
        java.lang.Object ref = interfaceVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          interfaceVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string interfaceVersion = 1;</code>
       */
      public com.google.protobuf.ByteString
          getInterfaceVersionBytes() {
        java.lang.Object ref = interfaceVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          interfaceVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string interfaceVersion = 1;</code>
       */
      public Builder setInterfaceVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        interfaceVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string interfaceVersion = 1;</code>
       */
      public Builder clearInterfaceVersion() {
        
        interfaceVersion_ = getDefaultInstance().getInterfaceVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string interfaceVersion = 1;</code>
       */
      public Builder setInterfaceVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        interfaceVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object couponUrl_ = "";
      /**
       * <code>optional string couponUrl = 2;</code>
       */
      public java.lang.String getCouponUrl() {
        java.lang.Object ref = couponUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          couponUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string couponUrl = 2;</code>
       */
      public com.google.protobuf.ByteString
          getCouponUrlBytes() {
        java.lang.Object ref = couponUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          couponUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string couponUrl = 2;</code>
       */
      public Builder setCouponUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        couponUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string couponUrl = 2;</code>
       */
      public Builder clearCouponUrl() {
        
        couponUrl_ = getDefaultInstance().getCouponUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string couponUrl = 2;</code>
       */
      public Builder setCouponUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        couponUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object taskUrl_ = "";
      /**
       * <code>optional string taskUrl = 3;</code>
       */
      public java.lang.String getTaskUrl() {
        java.lang.Object ref = taskUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          taskUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string taskUrl = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTaskUrlBytes() {
        java.lang.Object ref = taskUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string taskUrl = 3;</code>
       */
      public Builder setTaskUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskUrl = 3;</code>
       */
      public Builder clearTaskUrl() {
        
        taskUrl_ = getDefaultInstance().getTaskUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string taskUrl = 3;</code>
       */
      public Builder setTaskUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskUrl_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object baseUrl_ = "";
      /**
       * <code>optional string baseUrl = 4;</code>
       */
      public java.lang.String getBaseUrl() {
        java.lang.Object ref = baseUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          baseUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string baseUrl = 4;</code>
       */
      public com.google.protobuf.ByteString
          getBaseUrlBytes() {
        java.lang.Object ref = baseUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          baseUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string baseUrl = 4;</code>
       */
      public Builder setBaseUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        baseUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseUrl = 4;</code>
       */
      public Builder clearBaseUrl() {
        
        baseUrl_ = getDefaultInstance().getBaseUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string baseUrl = 4;</code>
       */
      public Builder setBaseUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        baseUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.GetGlobalConfigResponse)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.GetGlobalConfigResponse)
    private static final hr.client.appuser.GlobalConfig.GetGlobalConfigResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.GlobalConfig.GetGlobalConfigResponse();
    }

    public static hr.client.appuser.GlobalConfig.GetGlobalConfigResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetGlobalConfigResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetGlobalConfigResponse>() {
      public GetGlobalConfigResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GetGlobalConfigResponse(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GetGlobalConfigResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetGlobalConfigResponse> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.GlobalConfig.GetGlobalConfigResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetGlobalConfig_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetGlobalConfig_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_GetGlobalConfigResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022globalConfig.proto\022\021hr.client.appuser\"" +
      "%\n\017GetGlobalConfig\022\022\n\nappVersion\030\001 \001(\t\"h" +
      "\n\027GetGlobalConfigResponse\022\030\n\020interfaceVe" +
      "rsion\030\001 \001(\t\022\021\n\tcouponUrl\030\002 \001(\t\022\017\n\007taskUr" +
      "l\030\003 \001(\t\022\017\n\007baseUrl\030\004 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hr_client_appuser_GetGlobalConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_client_appuser_GetGlobalConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetGlobalConfig_descriptor,
        new java.lang.String[] { "AppVersion", });
    internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hr_client_appuser_GetGlobalConfigResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_GetGlobalConfigResponse_descriptor,
        new java.lang.String[] { "InterfaceVersion", "CouponUrl", "TaskUrl", "BaseUrl", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
