// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sessionInfo.proto

package hr.client.appuser;

@SuppressWarnings("unused")
public final class SessionInfoOuterClass {
  private SessionInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SessionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:hr.client.appuser.SessionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string userId = 1;</code>
     */
    java.lang.String getUserId();
    /**
     * <code>optional string userId = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdBytes();

    /**
     * <code>optional string accessToken = 2;</code>
     */
    java.lang.String getAccessToken();
    /**
     * <code>optional string accessToken = 2;</code>
     */
    com.google.protobuf.ByteString
        getAccessTokenBytes();

    /**
     * <code>optional string refreshToken = 3;</code>
     */
    java.lang.String getRefreshToken();
    /**
     * <code>optional string refreshToken = 3;</code>
     */
    com.google.protobuf.ByteString
        getRefreshTokenBytes();

    /**
     * <code>optional int32 expiresIn = 4;</code>
     */
    int getExpiresIn();

    /**
     * <code>optional string sessionId = 5;</code>
     */
    java.lang.String getSessionId();
    /**
     * <code>optional string sessionId = 5;</code>
     */
    com.google.protobuf.ByteString
        getSessionIdBytes();
  }
  /**
   * Protobuf type {@code hr.client.appuser.SessionInfo}
   */
  public  static final class SessionInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:hr.client.appuser.SessionInfo)
      SessionInfoOrBuilder {
    // Use SessionInfo.newBuilder() to construct.
    private SessionInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SessionInfo() {
      userId_ = "";
      accessToken_ = "";
      refreshToken_ = "";
      expiresIn_ = 0;
      sessionId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SessionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              userId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              accessToken_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              refreshToken_ = s;
              break;
            }
            case 32: {

              expiresIn_ = input.readInt32();
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              sessionId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return hr.client.appuser.SessionInfoOuterClass.internal_static_hr_client_appuser_SessionInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return hr.client.appuser.SessionInfoOuterClass.internal_static_hr_client_appuser_SessionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              hr.client.appuser.SessionInfoOuterClass.SessionInfo.class, hr.client.appuser.SessionInfoOuterClass.SessionInfo.Builder.class);
    }

    public static final int USERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userId_;
    /**
     * <code>optional string userId = 1;</code>
     */
    public java.lang.String getUserId() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string userId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdBytes() {
      java.lang.Object ref = userId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 2;
    private volatile java.lang.Object accessToken_;
    /**
     * <code>optional string accessToken = 2;</code>
     */
    public java.lang.String getAccessToken() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accessToken_ = s;
        return s;
      }
    }
    /**
     * <code>optional string accessToken = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAccessTokenBytes() {
      java.lang.Object ref = accessToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accessToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REFRESHTOKEN_FIELD_NUMBER = 3;
    private volatile java.lang.Object refreshToken_;
    /**
     * <code>optional string refreshToken = 3;</code>
     */
    public java.lang.String getRefreshToken() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        refreshToken_ = s;
        return s;
      }
    }
    /**
     * <code>optional string refreshToken = 3;</code>
     */
    public com.google.protobuf.ByteString
        getRefreshTokenBytes() {
      java.lang.Object ref = refreshToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        refreshToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXPIRESIN_FIELD_NUMBER = 4;
    private int expiresIn_;
    /**
     * <code>optional int32 expiresIn = 4;</code>
     */
    public int getExpiresIn() {
      return expiresIn_;
    }

    public static final int SESSIONID_FIELD_NUMBER = 5;
    private volatile java.lang.Object sessionId_;
    /**
     * <code>optional string sessionId = 5;</code>
     */
    public java.lang.String getSessionId() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        sessionId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string sessionId = 5;</code>
     */
    public com.google.protobuf.ByteString
        getSessionIdBytes() {
      java.lang.Object ref = sessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, userId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, accessToken_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, refreshToken_);
      }
      if (expiresIn_ != 0) {
        output.writeInt32(4, expiresIn_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, sessionId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, userId_);
      }
      if (!getAccessTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, accessToken_);
      }
      if (!getRefreshTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, refreshToken_);
      }
      if (expiresIn_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, expiresIn_);
      }
      if (!getSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, sessionId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(hr.client.appuser.SessionInfoOuterClass.SessionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code hr.client.appuser.SessionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:hr.client.appuser.SessionInfo)
        hr.client.appuser.SessionInfoOuterClass.SessionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return hr.client.appuser.SessionInfoOuterClass.internal_static_hr_client_appuser_SessionInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return hr.client.appuser.SessionInfoOuterClass.internal_static_hr_client_appuser_SessionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                hr.client.appuser.SessionInfoOuterClass.SessionInfo.class, hr.client.appuser.SessionInfoOuterClass.SessionInfo.Builder.class);
      }

      // Construct using hr.client.appuser.SessionInfoOuterClass.SessionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userId_ = "";

        accessToken_ = "";

        refreshToken_ = "";

        expiresIn_ = 0;

        sessionId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return hr.client.appuser.SessionInfoOuterClass.internal_static_hr_client_appuser_SessionInfo_descriptor;
      }

      public hr.client.appuser.SessionInfoOuterClass.SessionInfo getDefaultInstanceForType() {
        return hr.client.appuser.SessionInfoOuterClass.SessionInfo.getDefaultInstance();
      }

      public hr.client.appuser.SessionInfoOuterClass.SessionInfo build() {
        hr.client.appuser.SessionInfoOuterClass.SessionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public hr.client.appuser.SessionInfoOuterClass.SessionInfo buildPartial() {
        hr.client.appuser.SessionInfoOuterClass.SessionInfo result = new hr.client.appuser.SessionInfoOuterClass.SessionInfo(this);
        result.userId_ = userId_;
        result.accessToken_ = accessToken_;
        result.refreshToken_ = refreshToken_;
        result.expiresIn_ = expiresIn_;
        result.sessionId_ = sessionId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof hr.client.appuser.SessionInfoOuterClass.SessionInfo) {
          return mergeFrom((hr.client.appuser.SessionInfoOuterClass.SessionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(hr.client.appuser.SessionInfoOuterClass.SessionInfo other) {
        if (other == hr.client.appuser.SessionInfoOuterClass.SessionInfo.getDefaultInstance()) return this;
        if (!other.getUserId().isEmpty()) {
          userId_ = other.userId_;
          onChanged();
        }
        if (!other.getAccessToken().isEmpty()) {
          accessToken_ = other.accessToken_;
          onChanged();
        }
        if (!other.getRefreshToken().isEmpty()) {
          refreshToken_ = other.refreshToken_;
          onChanged();
        }
        if (other.getExpiresIn() != 0) {
          setExpiresIn(other.getExpiresIn());
        }
        if (!other.getSessionId().isEmpty()) {
          sessionId_ = other.sessionId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        hr.client.appuser.SessionInfoOuterClass.SessionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (hr.client.appuser.SessionInfoOuterClass.SessionInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userId_ = "";
      /**
       * <code>optional string userId = 1;</code>
       */
      public java.lang.String getUserId() {
        java.lang.Object ref = userId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdBytes() {
        java.lang.Object ref = userId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder clearUserId() {
        
        userId_ = getDefaultInstance().getUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userId = 1;</code>
       */
      public Builder setUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object accessToken_ = "";
      /**
       * <code>optional string accessToken = 2;</code>
       */
      public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          accessToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string accessToken = 2;</code>
       */
      public com.google.protobuf.ByteString
          getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          accessToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string accessToken = 2;</code>
       */
      public Builder setAccessToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        accessToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessToken = 2;</code>
       */
      public Builder clearAccessToken() {
        
        accessToken_ = getDefaultInstance().getAccessToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string accessToken = 2;</code>
       */
      public Builder setAccessTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        accessToken_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object refreshToken_ = "";
      /**
       * <code>optional string refreshToken = 3;</code>
       */
      public java.lang.String getRefreshToken() {
        java.lang.Object ref = refreshToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          refreshToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string refreshToken = 3;</code>
       */
      public com.google.protobuf.ByteString
          getRefreshTokenBytes() {
        java.lang.Object ref = refreshToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          refreshToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string refreshToken = 3;</code>
       */
      public Builder setRefreshToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refreshToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string refreshToken = 3;</code>
       */
      public Builder clearRefreshToken() {
        
        refreshToken_ = getDefaultInstance().getRefreshToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string refreshToken = 3;</code>
       */
      public Builder setRefreshTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        refreshToken_ = value;
        onChanged();
        return this;
      }

      private int expiresIn_ ;
      /**
       * <code>optional int32 expiresIn = 4;</code>
       */
      public int getExpiresIn() {
        return expiresIn_;
      }
      /**
       * <code>optional int32 expiresIn = 4;</code>
       */
      public Builder setExpiresIn(int value) {
        
        expiresIn_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expiresIn = 4;</code>
       */
      public Builder clearExpiresIn() {
        
        expiresIn_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object sessionId_ = "";
      /**
       * <code>optional string sessionId = 5;</code>
       */
      public java.lang.String getSessionId() {
        java.lang.Object ref = sessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       */
      public com.google.protobuf.ByteString
          getSessionIdBytes() {
        java.lang.Object ref = sessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sessionId = 5;</code>
       */
      public Builder setSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       */
      public Builder clearSessionId() {
        
        sessionId_ = getDefaultInstance().getSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sessionId = 5;</code>
       */
      public Builder setSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sessionId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:hr.client.appuser.SessionInfo)
    }

    // @@protoc_insertion_point(class_scope:hr.client.appuser.SessionInfo)
    private static final hr.client.appuser.SessionInfoOuterClass.SessionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new hr.client.appuser.SessionInfoOuterClass.SessionInfo();
    }

    public static hr.client.appuser.SessionInfoOuterClass.SessionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SessionInfo>
        PARSER = new com.google.protobuf.AbstractParser<SessionInfo>() {
      public SessionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SessionInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SessionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SessionInfo> getParserForType() {
      return PARSER;
    }

    public hr.client.appuser.SessionInfoOuterClass.SessionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_hr_client_appuser_SessionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_hr_client_appuser_SessionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021sessionInfo.proto\022\021hr.client.appuser\"n" +
      "\n\013SessionInfo\022\016\n\006userId\030\001 \001(\t\022\023\n\013accessT" +
      "oken\030\002 \001(\t\022\024\n\014refreshToken\030\003 \001(\t\022\021\n\texpi" +
      "resIn\030\004 \001(\005\022\021\n\tsessionId\030\005 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hr_client_appuser_SessionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hr_client_appuser_SessionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_hr_client_appuser_SessionInfo_descriptor,
        new java.lang.String[] { "UserId", "AccessToken", "RefreshToken", "ExpiresIn", "SessionId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
