// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package grpc.client;

@SuppressWarnings("unused")
public final class AppOuterClass {
  private AppOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code grpc.client.AppType}
   */
  public enum AppType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN_APPTYPE = 0;</code>
     */
    UNKNOWN_APPTYPE(0, 0),
    /**
     * <code>ANDROID_APP = 1;</code>
     */
    ANDROID_APP(1, 1),
    /**
     * <code>ANDROID_SDK_EMBEDED = 2;</code>
     */
    ANDROID_SDK_EMBEDED(2, 2),
    /**
     * <code>ANDROID_SDK = 3;</code>
     */
    ANDROID_SDK(3, 3),
    /**
     * <code>IOS_APP = 4;</code>
     */
    IOS_APP(4, 4),
    /**
     * <code>IOS_SDK_EMBEDED = 5;</code>
     */
    IOS_SDK_EMBEDED(5, 5),
    /**
     * <code>IOS_SDK = 6;</code>
     */
    IOS_SDK(6, 6),
    /**
     * <code>WIN_APP = 7;</code>
     */
    WIN_APP(7, 7),
    /**
     * <code>WIN_SDK_EMBEDED = 8;</code>
     */
    WIN_SDK_EMBEDED(8, 8),
    /**
     * <code>WIN_SDK = 9;</code>
     */
    WIN_SDK(9, 9),
    /**
     * <code>WEB_SDK = 10;</code>
     */
    WEB_SDK(10, 10),
    UNRECOGNIZED(-1, -1),
    ;

    /**
     * <code>UNKNOWN_APPTYPE = 0;</code>
     */
    public static final int UNKNOWN_APPTYPE_VALUE = 0;
    /**
     * <code>ANDROID_APP = 1;</code>
     */
    public static final int ANDROID_APP_VALUE = 1;
    /**
     * <code>ANDROID_SDK_EMBEDED = 2;</code>
     */
    public static final int ANDROID_SDK_EMBEDED_VALUE = 2;
    /**
     * <code>ANDROID_SDK = 3;</code>
     */
    public static final int ANDROID_SDK_VALUE = 3;
    /**
     * <code>IOS_APP = 4;</code>
     */
    public static final int IOS_APP_VALUE = 4;
    /**
     * <code>IOS_SDK_EMBEDED = 5;</code>
     */
    public static final int IOS_SDK_EMBEDED_VALUE = 5;
    /**
     * <code>IOS_SDK = 6;</code>
     */
    public static final int IOS_SDK_VALUE = 6;
    /**
     * <code>WIN_APP = 7;</code>
     */
    public static final int WIN_APP_VALUE = 7;
    /**
     * <code>WIN_SDK_EMBEDED = 8;</code>
     */
    public static final int WIN_SDK_EMBEDED_VALUE = 8;
    /**
     * <code>WIN_SDK = 9;</code>
     */
    public static final int WIN_SDK_VALUE = 9;
    /**
     * <code>WEB_SDK = 10;</code>
     */
    public static final int WEB_SDK_VALUE = 10;


    public final int getNumber() {
      if (index == -1) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    public static AppType valueOf(int value) {
      switch (value) {
        case 0: return UNKNOWN_APPTYPE;
        case 1: return ANDROID_APP;
        case 2: return ANDROID_SDK_EMBEDED;
        case 3: return ANDROID_SDK;
        case 4: return IOS_APP;
        case 5: return IOS_SDK_EMBEDED;
        case 6: return IOS_SDK;
        case 7: return WIN_APP;
        case 8: return WIN_SDK_EMBEDED;
        case 9: return WIN_SDK;
        case 10: return WEB_SDK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AppType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        AppType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AppType>() {
            public AppType findValueByNumber(int number) {
              return AppType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.client.AppOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final AppType[] VALUES = values();

    public static AppType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private AppType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:grpc.client.AppType)
  }

  public interface AppOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.client.App)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string AppLabel = 1;</code>
     */
    java.lang.String getAppLabel();
    /**
     * <code>optional string AppLabel = 1;</code>
     */
    com.google.protobuf.ByteString
        getAppLabelBytes();

    /**
     * <code>optional string PkgName = 2;</code>
     */
    java.lang.String getPkgName();
    /**
     * <code>optional string PkgName = 2;</code>
     */
    com.google.protobuf.ByteString
        getPkgNameBytes();
  }
  /**
   * Protobuf type {@code grpc.client.App}
   */
  public  static final class App extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpc.client.App)
      AppOrBuilder {
    // Use App.newBuilder() to construct.
    private App(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private App() {
      appLabel_ = "";
      pkgName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private App(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              appLabel_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              pkgName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.AppOuterClass.internal_static_grpc_client_App_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.AppOuterClass.internal_static_grpc_client_App_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.AppOuterClass.App.class, grpc.client.AppOuterClass.App.Builder.class);
    }

    public static final int APPLABEL_FIELD_NUMBER = 1;
    private volatile java.lang.Object appLabel_;
    /**
     * <code>optional string AppLabel = 1;</code>
     */
    public java.lang.String getAppLabel() {
      java.lang.Object ref = appLabel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        appLabel_ = s;
        return s;
      }
    }
    /**
     * <code>optional string AppLabel = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAppLabelBytes() {
      java.lang.Object ref = appLabel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        appLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PKGNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object pkgName_;
    /**
     * <code>optional string PkgName = 2;</code>
     */
    public java.lang.String getPkgName() {
      java.lang.Object ref = pkgName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pkgName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string PkgName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPkgNameBytes() {
      java.lang.Object ref = pkgName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pkgName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getAppLabelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, appLabel_);
      }
      if (!getPkgNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, pkgName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAppLabelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, appLabel_);
      }
      if (!getPkgNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, pkgName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static grpc.client.AppOuterClass.App parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.AppOuterClass.App parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.AppOuterClass.App parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.AppOuterClass.App parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.AppOuterClass.App parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.AppOuterClass.App parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static grpc.client.AppOuterClass.App parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static grpc.client.AppOuterClass.App parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static grpc.client.AppOuterClass.App parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.AppOuterClass.App parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.client.AppOuterClass.App prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.client.App}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.client.App)
        grpc.client.AppOuterClass.AppOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.client.AppOuterClass.internal_static_grpc_client_App_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.client.AppOuterClass.internal_static_grpc_client_App_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.client.AppOuterClass.App.class, grpc.client.AppOuterClass.App.Builder.class);
      }

      // Construct using grpc.client.AppOuterClass.App.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        appLabel_ = "";

        pkgName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.client.AppOuterClass.internal_static_grpc_client_App_descriptor;
      }

      public grpc.client.AppOuterClass.App getDefaultInstanceForType() {
        return grpc.client.AppOuterClass.App.getDefaultInstance();
      }

      public grpc.client.AppOuterClass.App build() {
        grpc.client.AppOuterClass.App result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.client.AppOuterClass.App buildPartial() {
        grpc.client.AppOuterClass.App result = new grpc.client.AppOuterClass.App(this);
        result.appLabel_ = appLabel_;
        result.pkgName_ = pkgName_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.client.AppOuterClass.App) {
          return mergeFrom((grpc.client.AppOuterClass.App)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.client.AppOuterClass.App other) {
        if (other == grpc.client.AppOuterClass.App.getDefaultInstance()) return this;
        if (!other.getAppLabel().isEmpty()) {
          appLabel_ = other.appLabel_;
          onChanged();
        }
        if (!other.getPkgName().isEmpty()) {
          pkgName_ = other.pkgName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.client.AppOuterClass.App parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.client.AppOuterClass.App) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object appLabel_ = "";
      /**
       * <code>optional string AppLabel = 1;</code>
       */
      public java.lang.String getAppLabel() {
        java.lang.Object ref = appLabel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          appLabel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string AppLabel = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAppLabelBytes() {
        java.lang.Object ref = appLabel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          appLabel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string AppLabel = 1;</code>
       */
      public Builder setAppLabel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        appLabel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string AppLabel = 1;</code>
       */
      public Builder clearAppLabel() {
        
        appLabel_ = getDefaultInstance().getAppLabel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string AppLabel = 1;</code>
       */
      public Builder setAppLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        appLabel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pkgName_ = "";
      /**
       * <code>optional string PkgName = 2;</code>
       */
      public java.lang.String getPkgName() {
        java.lang.Object ref = pkgName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pkgName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string PkgName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPkgNameBytes() {
        java.lang.Object ref = pkgName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pkgName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string PkgName = 2;</code>
       */
      public Builder setPkgName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pkgName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string PkgName = 2;</code>
       */
      public Builder clearPkgName() {
        
        pkgName_ = getDefaultInstance().getPkgName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string PkgName = 2;</code>
       */
      public Builder setPkgNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pkgName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpc.client.App)
    }

    // @@protoc_insertion_point(class_scope:grpc.client.App)
    private static final grpc.client.AppOuterClass.App DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.client.AppOuterClass.App();
    }

    public static grpc.client.AppOuterClass.App getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<App>
        PARSER = new com.google.protobuf.AbstractParser<App>() {
      public App parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new App(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<App> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<App> getParserForType() {
      return PARSER;
    }

    public grpc.client.AppOuterClass.App getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_client_App_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_client_App_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapp.proto\022\013grpc.client\"(\n\003App\022\020\n\010AppLa" +
      "bel\030\001 \001(\t\022\017\n\007PkgName\030\002 \001(\t*\304\001\n\007AppType\022\023" +
      "\n\017UNKNOWN_APPTYPE\020\000\022\017\n\013ANDROID_APP\020\001\022\027\n\023" +
      "ANDROID_SDK_EMBEDED\020\002\022\017\n\013ANDROID_SDK\020\003\022\013" +
      "\n\007IOS_APP\020\004\022\023\n\017IOS_SDK_EMBEDED\020\005\022\013\n\007IOS_" +
      "SDK\020\006\022\013\n\007WIN_APP\020\007\022\023\n\017WIN_SDK_EMBEDED\020\010\022" +
      "\013\n\007WIN_SDK\020\t\022\013\n\007WEB_SDK\020\nb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_client_App_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_client_App_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_client_App_descriptor,
        new java.lang.String[] { "AppLabel", "PkgName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
