// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: upgrade.proto

package grpc.client;

@SuppressWarnings("unused")
public final class Upgrade {
  private Upgrade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface UpgradeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.client.UpgradeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    grpc.client.Id.SubaoId getId();
    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    grpc.client.Id.SubaoIdOrBuilder getIdOrBuilder();

    /**
     * <code>optional uint64 time = 2;</code>
     *
     * <pre>
     *unix time
     * </pre>
     */
    long getTime();

    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    boolean hasOldVersion();
    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    grpc.client.Version.VersionInfo getOldVersion();
    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    grpc.client.Version.VersionInfoOrBuilder getOldVersionOrBuilder();

    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    boolean hasNewVersion();
    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    grpc.client.Version.VersionInfo getNewVersion();
    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    grpc.client.Version.VersionInfoOrBuilder getNewVersionOrBuilder();

    /**
     * <code>optional .grpc.client.AppType type = 5;</code>
     */
    int getTypeValue();
    /**
     * <code>optional .grpc.client.AppType type = 5;</code>
     */
    grpc.client.AppOuterClass.AppType getType();
  }
  /**
   * Protobuf type {@code grpc.client.UpgradeMsg}
   *
   * <pre>
   *SDK无该消息
   * </pre>
   */
  public  static final class UpgradeMsg extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpc.client.UpgradeMsg)
      UpgradeMsgOrBuilder {
    // Use UpgradeMsg.newBuilder() to construct.
    private UpgradeMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UpgradeMsg() {
      time_ = 0L;
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpgradeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              grpc.client.Id.SubaoId.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(grpc.client.Id.SubaoId.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              time_ = input.readUInt64();
              break;
            }
            case 26: {
              grpc.client.Version.VersionInfo.Builder subBuilder = null;
              if (oldVersion_ != null) {
                subBuilder = oldVersion_.toBuilder();
              }
              oldVersion_ = input.readMessage(grpc.client.Version.VersionInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(oldVersion_);
                oldVersion_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              grpc.client.Version.VersionInfo.Builder subBuilder = null;
              if (newVersion_ != null) {
                subBuilder = newVersion_.toBuilder();
              }
              newVersion_ = input.readMessage(grpc.client.Version.VersionInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(newVersion_);
                newVersion_ = subBuilder.buildPartial();
              }

              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.Upgrade.internal_static_grpc_client_UpgradeMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.Upgrade.internal_static_grpc_client_UpgradeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.Upgrade.UpgradeMsg.class, grpc.client.Upgrade.UpgradeMsg.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private grpc.client.Id.SubaoId id_;
    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    public grpc.client.Id.SubaoId getId() {
      return id_ == null ? grpc.client.Id.SubaoId.getDefaultInstance() : id_;
    }
    /**
     * <code>optional .grpc.client.SubaoId id = 1;</code>
     */
    public grpc.client.Id.SubaoIdOrBuilder getIdOrBuilder() {
      return getId();
    }

    public static final int TIME_FIELD_NUMBER = 2;
    private long time_;
    /**
     * <code>optional uint64 time = 2;</code>
     *
     * <pre>
     *unix time
     * </pre>
     */
    public long getTime() {
      return time_;
    }

    public static final int OLDVERSION_FIELD_NUMBER = 3;
    private grpc.client.Version.VersionInfo oldVersion_;
    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    public boolean hasOldVersion() {
      return oldVersion_ != null;
    }
    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    public grpc.client.Version.VersionInfo getOldVersion() {
      return oldVersion_ == null ? grpc.client.Version.VersionInfo.getDefaultInstance() : oldVersion_;
    }
    /**
     * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
     */
    public grpc.client.Version.VersionInfoOrBuilder getOldVersionOrBuilder() {
      return getOldVersion();
    }

    public static final int NEWVERSION_FIELD_NUMBER = 4;
    private grpc.client.Version.VersionInfo newVersion_;
    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    public boolean hasNewVersion() {
      return newVersion_ != null;
    }
    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    public grpc.client.Version.VersionInfo getNewVersion() {
      return newVersion_ == null ? grpc.client.Version.VersionInfo.getDefaultInstance() : newVersion_;
    }
    /**
     * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
     */
    public grpc.client.Version.VersionInfoOrBuilder getNewVersionOrBuilder() {
      return getNewVersion();
    }

    public static final int TYPE_FIELD_NUMBER = 5;
    private int type_;
    /**
     * <code>optional .grpc.client.AppType type = 5;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .grpc.client.AppType type = 5;</code>
     */
    public grpc.client.AppOuterClass.AppType getType() {
      grpc.client.AppOuterClass.AppType result = grpc.client.AppOuterClass.AppType.valueOf(type_);
      return result == null ? grpc.client.AppOuterClass.AppType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (time_ != 0L) {
        output.writeUInt64(2, time_);
      }
      if (oldVersion_ != null) {
        output.writeMessage(3, getOldVersion());
      }
      if (newVersion_ != null) {
        output.writeMessage(4, getNewVersion());
      }
      if (type_ != grpc.client.AppOuterClass.AppType.UNKNOWN_APPTYPE.getNumber()) {
        output.writeEnum(5, type_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, time_);
      }
      if (oldVersion_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getOldVersion());
      }
      if (newVersion_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getNewVersion());
      }
      if (type_ != grpc.client.AppOuterClass.AppType.UNKNOWN_APPTYPE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, type_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.client.Upgrade.UpgradeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.client.UpgradeMsg}
     *
     * <pre>
     *SDK无该消息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.client.UpgradeMsg)
        grpc.client.Upgrade.UpgradeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.client.Upgrade.UpgradeMsg.class, grpc.client.Upgrade.UpgradeMsg.Builder.class);
      }

      // Construct using grpc.client.Upgrade.UpgradeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        time_ = 0L;

        if (oldVersionBuilder_ == null) {
          oldVersion_ = null;
        } else {
          oldVersion_ = null;
          oldVersionBuilder_ = null;
        }
        if (newVersionBuilder_ == null) {
          newVersion_ = null;
        } else {
          newVersion_ = null;
          newVersionBuilder_ = null;
        }
        type_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeMsg_descriptor;
      }

      public grpc.client.Upgrade.UpgradeMsg getDefaultInstanceForType() {
        return grpc.client.Upgrade.UpgradeMsg.getDefaultInstance();
      }

      public grpc.client.Upgrade.UpgradeMsg build() {
        grpc.client.Upgrade.UpgradeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.client.Upgrade.UpgradeMsg buildPartial() {
        grpc.client.Upgrade.UpgradeMsg result = new grpc.client.Upgrade.UpgradeMsg(this);
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        result.time_ = time_;
        if (oldVersionBuilder_ == null) {
          result.oldVersion_ = oldVersion_;
        } else {
          result.oldVersion_ = oldVersionBuilder_.build();
        }
        if (newVersionBuilder_ == null) {
          result.newVersion_ = newVersion_;
        } else {
          result.newVersion_ = newVersionBuilder_.build();
        }
        result.type_ = type_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.client.Upgrade.UpgradeMsg) {
          return mergeFrom((grpc.client.Upgrade.UpgradeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.client.Upgrade.UpgradeMsg other) {
        if (other == grpc.client.Upgrade.UpgradeMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.hasOldVersion()) {
          mergeOldVersion(other.getOldVersion());
        }
        if (other.hasNewVersion()) {
          mergeNewVersion(other.getNewVersion());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.client.Upgrade.UpgradeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.client.Upgrade.UpgradeMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private grpc.client.Id.SubaoId id_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Id.SubaoId, grpc.client.Id.SubaoId.Builder, grpc.client.Id.SubaoIdOrBuilder> idBuilder_;
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public grpc.client.Id.SubaoId getId() {
        if (idBuilder_ == null) {
          return id_ == null ? grpc.client.Id.SubaoId.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public Builder setId(grpc.client.Id.SubaoId value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public Builder setId(
          grpc.client.Id.SubaoId.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public Builder mergeId(grpc.client.Id.SubaoId value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              grpc.client.Id.SubaoId.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public grpc.client.Id.SubaoId.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      public grpc.client.Id.SubaoIdOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              grpc.client.Id.SubaoId.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>optional .grpc.client.SubaoId id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Id.SubaoId, grpc.client.Id.SubaoId.Builder, grpc.client.Id.SubaoIdOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              grpc.client.Id.SubaoId, grpc.client.Id.SubaoId.Builder, grpc.client.Id.SubaoIdOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private long time_ ;
      /**
       * <code>optional uint64 time = 2;</code>
       *
       * <pre>
       *unix time
       * </pre>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>optional uint64 time = 2;</code>
       *
       * <pre>
       *unix time
       * </pre>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 time = 2;</code>
       *
       * <pre>
       *unix time
       * </pre>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private grpc.client.Version.VersionInfo oldVersion_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder> oldVersionBuilder_;
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public boolean hasOldVersion() {
        return oldVersionBuilder_ != null || oldVersion_ != null;
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public grpc.client.Version.VersionInfo getOldVersion() {
        if (oldVersionBuilder_ == null) {
          return oldVersion_ == null ? grpc.client.Version.VersionInfo.getDefaultInstance() : oldVersion_;
        } else {
          return oldVersionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public Builder setOldVersion(grpc.client.Version.VersionInfo value) {
        if (oldVersionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          oldVersion_ = value;
          onChanged();
        } else {
          oldVersionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public Builder setOldVersion(
          grpc.client.Version.VersionInfo.Builder builderForValue) {
        if (oldVersionBuilder_ == null) {
          oldVersion_ = builderForValue.build();
          onChanged();
        } else {
          oldVersionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public Builder mergeOldVersion(grpc.client.Version.VersionInfo value) {
        if (oldVersionBuilder_ == null) {
          if (oldVersion_ != null) {
            oldVersion_ =
              grpc.client.Version.VersionInfo.newBuilder(oldVersion_).mergeFrom(value).buildPartial();
          } else {
            oldVersion_ = value;
          }
          onChanged();
        } else {
          oldVersionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public Builder clearOldVersion() {
        if (oldVersionBuilder_ == null) {
          oldVersion_ = null;
          onChanged();
        } else {
          oldVersion_ = null;
          oldVersionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public grpc.client.Version.VersionInfo.Builder getOldVersionBuilder() {
        
        onChanged();
        return getOldVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      public grpc.client.Version.VersionInfoOrBuilder getOldVersionOrBuilder() {
        if (oldVersionBuilder_ != null) {
          return oldVersionBuilder_.getMessageOrBuilder();
        } else {
          return oldVersion_ == null ?
              grpc.client.Version.VersionInfo.getDefaultInstance() : oldVersion_;
        }
      }
      /**
       * <code>optional .grpc.client.VersionInfo oldVersion = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder> 
          getOldVersionFieldBuilder() {
        if (oldVersionBuilder_ == null) {
          oldVersionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder>(
                  getOldVersion(),
                  getParentForChildren(),
                  isClean());
          oldVersion_ = null;
        }
        return oldVersionBuilder_;
      }

      private grpc.client.Version.VersionInfo newVersion_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder> newVersionBuilder_;
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public boolean hasNewVersion() {
        return newVersionBuilder_ != null || newVersion_ != null;
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public grpc.client.Version.VersionInfo getNewVersion() {
        if (newVersionBuilder_ == null) {
          return newVersion_ == null ? grpc.client.Version.VersionInfo.getDefaultInstance() : newVersion_;
        } else {
          return newVersionBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public Builder setNewVersion(grpc.client.Version.VersionInfo value) {
        if (newVersionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          newVersion_ = value;
          onChanged();
        } else {
          newVersionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public Builder setNewVersion(
          grpc.client.Version.VersionInfo.Builder builderForValue) {
        if (newVersionBuilder_ == null) {
          newVersion_ = builderForValue.build();
          onChanged();
        } else {
          newVersionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public Builder mergeNewVersion(grpc.client.Version.VersionInfo value) {
        if (newVersionBuilder_ == null) {
          if (newVersion_ != null) {
            newVersion_ =
              grpc.client.Version.VersionInfo.newBuilder(newVersion_).mergeFrom(value).buildPartial();
          } else {
            newVersion_ = value;
          }
          onChanged();
        } else {
          newVersionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public Builder clearNewVersion() {
        if (newVersionBuilder_ == null) {
          newVersion_ = null;
          onChanged();
        } else {
          newVersion_ = null;
          newVersionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public grpc.client.Version.VersionInfo.Builder getNewVersionBuilder() {
        
        onChanged();
        return getNewVersionFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      public grpc.client.Version.VersionInfoOrBuilder getNewVersionOrBuilder() {
        if (newVersionBuilder_ != null) {
          return newVersionBuilder_.getMessageOrBuilder();
        } else {
          return newVersion_ == null ?
              grpc.client.Version.VersionInfo.getDefaultInstance() : newVersion_;
        }
      }
      /**
       * <code>optional .grpc.client.VersionInfo newVersion = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder> 
          getNewVersionFieldBuilder() {
        if (newVersionBuilder_ == null) {
          newVersionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              grpc.client.Version.VersionInfo, grpc.client.Version.VersionInfo.Builder, grpc.client.Version.VersionInfoOrBuilder>(
                  getNewVersion(),
                  getParentForChildren(),
                  isClean());
          newVersion_ = null;
        }
        return newVersionBuilder_;
      }

      private int type_ = 0;
      /**
       * <code>optional .grpc.client.AppType type = 5;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>optional .grpc.client.AppType type = 5;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .grpc.client.AppType type = 5;</code>
       */
      public grpc.client.AppOuterClass.AppType getType() {
        grpc.client.AppOuterClass.AppType result = grpc.client.AppOuterClass.AppType.valueOf(type_);
        return result == null ? grpc.client.AppOuterClass.AppType.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .grpc.client.AppType type = 5;</code>
       */
      public Builder setType(grpc.client.AppOuterClass.AppType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .grpc.client.AppType type = 5;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpc.client.UpgradeMsg)
    }

    // @@protoc_insertion_point(class_scope:grpc.client.UpgradeMsg)
    private static final grpc.client.Upgrade.UpgradeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.client.Upgrade.UpgradeMsg();
    }

    public static grpc.client.Upgrade.UpgradeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpgradeMsg>
        PARSER = new com.google.protobuf.AbstractParser<UpgradeMsg>() {
      public UpgradeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpgradeMsg(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UpgradeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpgradeMsg> getParserForType() {
      return PARSER;
    }

    public grpc.client.Upgrade.UpgradeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UpgradeReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.client.UpgradeReply)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code grpc.client.UpgradeReply}
   */
  public  static final class UpgradeReply extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpc.client.UpgradeReply)
      UpgradeReplyOrBuilder {
    // Use UpgradeReply.newBuilder() to construct.
    private UpgradeReply(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UpgradeReply() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UpgradeReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.Upgrade.internal_static_grpc_client_UpgradeReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.Upgrade.internal_static_grpc_client_UpgradeReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.Upgrade.UpgradeReply.class, grpc.client.Upgrade.UpgradeReply.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Upgrade.UpgradeReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.client.Upgrade.UpgradeReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.client.UpgradeReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.client.UpgradeReply)
        grpc.client.Upgrade.UpgradeReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeReply_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.client.Upgrade.UpgradeReply.class, grpc.client.Upgrade.UpgradeReply.Builder.class);
      }

      // Construct using grpc.client.Upgrade.UpgradeReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.client.Upgrade.internal_static_grpc_client_UpgradeReply_descriptor;
      }

      public grpc.client.Upgrade.UpgradeReply getDefaultInstanceForType() {
        return grpc.client.Upgrade.UpgradeReply.getDefaultInstance();
      }

      public grpc.client.Upgrade.UpgradeReply build() {
        grpc.client.Upgrade.UpgradeReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.client.Upgrade.UpgradeReply buildPartial() {
        grpc.client.Upgrade.UpgradeReply result = new grpc.client.Upgrade.UpgradeReply(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.client.Upgrade.UpgradeReply) {
          return mergeFrom((grpc.client.Upgrade.UpgradeReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.client.Upgrade.UpgradeReply other) {
        if (other == grpc.client.Upgrade.UpgradeReply.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.client.Upgrade.UpgradeReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.client.Upgrade.UpgradeReply) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpc.client.UpgradeReply)
    }

    // @@protoc_insertion_point(class_scope:grpc.client.UpgradeReply)
    private static final grpc.client.Upgrade.UpgradeReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.client.Upgrade.UpgradeReply();
    }

    public static grpc.client.Upgrade.UpgradeReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UpgradeReply>
        PARSER = new com.google.protobuf.AbstractParser<UpgradeReply>() {
      public UpgradeReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new UpgradeReply(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<UpgradeReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UpgradeReply> getParserForType() {
      return PARSER;
    }

    public grpc.client.Upgrade.UpgradeReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_client_UpgradeMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_client_UpgradeMsg_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_client_UpgradeReply_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_client_UpgradeReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rupgrade.proto\022\013grpc.client\032\010id.proto\032\t" +
      "app.proto\032\rversion.proto\"\274\001\n\nUpgradeMsg\022" +
      " \n\002id\030\001 \001(\0132\024.grpc.client.SubaoId\022\014\n\004tim" +
      "e\030\002 \001(\004\022,\n\noldVersion\030\003 \001(\0132\030.grpc.clien" +
      "t.VersionInfo\022,\n\nnewVersion\030\004 \001(\0132\030.grpc" +
      ".client.VersionInfo\022\"\n\004type\030\005 \001(\0162\024.grpc" +
      ".client.AppType\"\016\n\014UpgradeReplyb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          grpc.client.Id.getDescriptor(),
          grpc.client.AppOuterClass.getDescriptor(),
          grpc.client.Version.getDescriptor(),
        }, assigner);
    internal_static_grpc_client_UpgradeMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_client_UpgradeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_client_UpgradeMsg_descriptor,
        new java.lang.String[] { "Id", "Time", "OldVersion", "NewVersion", "Type", });
    internal_static_grpc_client_UpgradeReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_client_UpgradeReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_client_UpgradeReply_descriptor,
        new java.lang.String[] { });
    grpc.client.Id.getDescriptor();
    grpc.client.AppOuterClass.getDescriptor();
    grpc.client.Version.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
