// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: version.proto

package grpc.client;

@SuppressWarnings("unused")
public final class Version {
  private Version() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VersionInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:grpc.client.VersionInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string number = 1;</code>
     *
     * <pre>
     *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
     * </pre>
     */
    java.lang.String getNumber();
    /**
     * <code>optional string number = 1;</code>
     *
     * <pre>
     *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
     * </pre>
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <code>optional string channel = 2;</code>
     *
     * <pre>
     *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
     * </pre>
     */
    java.lang.String getChannel();
    /**
     * <code>optional string channel = 2;</code>
     *
     * <pre>
     *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
     * </pre>
     */
    com.google.protobuf.ByteString
        getChannelBytes();

    /**
     * <code>optional string osVersion = 3;</code>
     *
     * <pre>
     *操作系统版本，如：MIUI 7.0等
     * </pre>
     */
    java.lang.String getOsVersion();
    /**
     * <code>optional string osVersion = 3;</code>
     *
     * <pre>
     *操作系统版本，如：MIUI 7.0等
     * </pre>
     */
    com.google.protobuf.ByteString
        getOsVersionBytes();

    /**
     * <code>optional string androidVersion = 4;</code>
     *
     * <pre>
     *安卓版本，如：22（5.1 lollipop）等
     * </pre>
     */
    java.lang.String getAndroidVersion();
    /**
     * <code>optional string androidVersion = 4;</code>
     *
     * <pre>
     *安卓版本，如：22（5.1 lollipop）等
     * </pre>
     */
    com.google.protobuf.ByteString
        getAndroidVersionBytes();
  }
  /**
   * Protobuf type {@code grpc.client.VersionInfo}
   */
  public  static final class VersionInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:grpc.client.VersionInfo)
      VersionInfoOrBuilder {
    // Use VersionInfo.newBuilder() to construct.
    private VersionInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VersionInfo() {
      number_ = "";
      channel_ = "";
      osVersion_ = "";
      androidVersion_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VersionInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              number_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              channel_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              osVersion_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              androidVersion_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.client.Version.internal_static_grpc_client_VersionInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.client.Version.internal_static_grpc_client_VersionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.client.Version.VersionInfo.class, grpc.client.Version.VersionInfo.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <code>optional string number = 1;</code>
     *
     * <pre>
     *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
     * </pre>
     */
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <code>optional string number = 1;</code>
     *
     * <pre>
     *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CHANNEL_FIELD_NUMBER = 2;
    private volatile java.lang.Object channel_;
    /**
     * <code>optional string channel = 2;</code>
     *
     * <pre>
     *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
     * </pre>
     */
    public java.lang.String getChannel() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        channel_ = s;
        return s;
      }
    }
    /**
     * <code>optional string channel = 2;</code>
     *
     * <pre>
     *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
     * </pre>
     */
    public com.google.protobuf.ByteString
        getChannelBytes() {
      java.lang.Object ref = channel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        channel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OSVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object osVersion_;
    /**
     * <code>optional string osVersion = 3;</code>
     *
     * <pre>
     *操作系统版本，如：MIUI 7.0等
     * </pre>
     */
    public java.lang.String getOsVersion() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        osVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string osVersion = 3;</code>
     *
     * <pre>
     *操作系统版本，如：MIUI 7.0等
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOsVersionBytes() {
      java.lang.Object ref = osVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        osVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANDROIDVERSION_FIELD_NUMBER = 4;
    private volatile java.lang.Object androidVersion_;
    /**
     * <code>optional string androidVersion = 4;</code>
     *
     * <pre>
     *安卓版本，如：22（5.1 lollipop）等
     * </pre>
     */
    public java.lang.String getAndroidVersion() {
      java.lang.Object ref = androidVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        androidVersion_ = s;
        return s;
      }
    }
    /**
     * <code>optional string androidVersion = 4;</code>
     *
     * <pre>
     *安卓版本，如：22（5.1 lollipop）等
     * </pre>
     */
    public com.google.protobuf.ByteString
        getAndroidVersionBytes() {
      java.lang.Object ref = androidVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        androidVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNumberBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, number_);
      }
      if (!getChannelBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, channel_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, osVersion_);
      }
      if (!getAndroidVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, androidVersion_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNumberBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, number_);
      }
      if (!getChannelBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, channel_);
      }
      if (!getOsVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, osVersion_);
      }
      if (!getAndroidVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, androidVersion_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static grpc.client.Version.VersionInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Version.VersionInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Version.VersionInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static grpc.client.Version.VersionInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static grpc.client.Version.VersionInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Version.VersionInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static grpc.client.Version.VersionInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static grpc.client.Version.VersionInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static grpc.client.Version.VersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static grpc.client.Version.VersionInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(grpc.client.Version.VersionInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code grpc.client.VersionInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:grpc.client.VersionInfo)
        grpc.client.Version.VersionInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return grpc.client.Version.internal_static_grpc_client_VersionInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return grpc.client.Version.internal_static_grpc_client_VersionInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                grpc.client.Version.VersionInfo.class, grpc.client.Version.VersionInfo.Builder.class);
      }

      // Construct using grpc.client.Version.VersionInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        number_ = "";

        channel_ = "";

        osVersion_ = "";

        androidVersion_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return grpc.client.Version.internal_static_grpc_client_VersionInfo_descriptor;
      }

      public grpc.client.Version.VersionInfo getDefaultInstanceForType() {
        return grpc.client.Version.VersionInfo.getDefaultInstance();
      }

      public grpc.client.Version.VersionInfo build() {
        grpc.client.Version.VersionInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public grpc.client.Version.VersionInfo buildPartial() {
        grpc.client.Version.VersionInfo result = new grpc.client.Version.VersionInfo(this);
        result.number_ = number_;
        result.channel_ = channel_;
        result.osVersion_ = osVersion_;
        result.androidVersion_ = androidVersion_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof grpc.client.Version.VersionInfo) {
          return mergeFrom((grpc.client.Version.VersionInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(grpc.client.Version.VersionInfo other) {
        if (other == grpc.client.Version.VersionInfo.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (!other.getChannel().isEmpty()) {
          channel_ = other.channel_;
          onChanged();
        }
        if (!other.getOsVersion().isEmpty()) {
          osVersion_ = other.osVersion_;
          onChanged();
        }
        if (!other.getAndroidVersion().isEmpty()) {
          androidVersion_ = other.androidVersion_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        grpc.client.Version.VersionInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (grpc.client.Version.VersionInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <code>optional string number = 1;</code>
       *
       * <pre>
       *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
       * </pre>
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       *
       * <pre>
       *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string number = 1;</code>
       *
       * <pre>
       *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
       * </pre>
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       *
       * <pre>
       *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
       * </pre>
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional string number = 1;</code>
       *
       * <pre>
       *版本号，如：3.5.1，3.6.1，SDK_1.0.0等
       * </pre>
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object channel_ = "";
      /**
       * <code>optional string channel = 2;</code>
       *
       * <pre>
       *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
       * </pre>
       */
      public java.lang.String getChannel() {
        java.lang.Object ref = channel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          channel_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string channel = 2;</code>
       *
       * <pre>
       *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
       * </pre>
       */
      public com.google.protobuf.ByteString
          getChannelBytes() {
        java.lang.Object ref = channel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          channel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string channel = 2;</code>
       *
       * <pre>
       *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
       * </pre>
       */
      public Builder setChannel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        channel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 2;</code>
       *
       * <pre>
       *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
       * </pre>
       */
      public Builder clearChannel() {
        
        channel_ = getDefaultInstance().getChannel();
        onChanged();
        return this;
      }
      /**
       * <code>optional string channel = 2;</code>
       *
       * <pre>
       *渠道名，如：BAIDU，XIAOMI，SDK_GUID等
       * </pre>
       */
      public Builder setChannelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        channel_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object osVersion_ = "";
      /**
       * <code>optional string osVersion = 3;</code>
       *
       * <pre>
       *操作系统版本，如：MIUI 7.0等
       * </pre>
       */
      public java.lang.String getOsVersion() {
        java.lang.Object ref = osVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          osVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string osVersion = 3;</code>
       *
       * <pre>
       *操作系统版本，如：MIUI 7.0等
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOsVersionBytes() {
        java.lang.Object ref = osVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          osVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string osVersion = 3;</code>
       *
       * <pre>
       *操作系统版本，如：MIUI 7.0等
       * </pre>
       */
      public Builder setOsVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        osVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string osVersion = 3;</code>
       *
       * <pre>
       *操作系统版本，如：MIUI 7.0等
       * </pre>
       */
      public Builder clearOsVersion() {
        
        osVersion_ = getDefaultInstance().getOsVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string osVersion = 3;</code>
       *
       * <pre>
       *操作系统版本，如：MIUI 7.0等
       * </pre>
       */
      public Builder setOsVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        osVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object androidVersion_ = "";
      /**
       * <code>optional string androidVersion = 4;</code>
       *
       * <pre>
       *安卓版本，如：22（5.1 lollipop）等
       * </pre>
       */
      public java.lang.String getAndroidVersion() {
        java.lang.Object ref = androidVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          androidVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string androidVersion = 4;</code>
       *
       * <pre>
       *安卓版本，如：22（5.1 lollipop）等
       * </pre>
       */
      public com.google.protobuf.ByteString
          getAndroidVersionBytes() {
        java.lang.Object ref = androidVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          androidVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string androidVersion = 4;</code>
       *
       * <pre>
       *安卓版本，如：22（5.1 lollipop）等
       * </pre>
       */
      public Builder setAndroidVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        androidVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string androidVersion = 4;</code>
       *
       * <pre>
       *安卓版本，如：22（5.1 lollipop）等
       * </pre>
       */
      public Builder clearAndroidVersion() {
        
        androidVersion_ = getDefaultInstance().getAndroidVersion();
        onChanged();
        return this;
      }
      /**
       * <code>optional string androidVersion = 4;</code>
       *
       * <pre>
       *安卓版本，如：22（5.1 lollipop）等
       * </pre>
       */
      public Builder setAndroidVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        androidVersion_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:grpc.client.VersionInfo)
    }

    // @@protoc_insertion_point(class_scope:grpc.client.VersionInfo)
    private static final grpc.client.Version.VersionInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new grpc.client.Version.VersionInfo();
    }

    public static grpc.client.Version.VersionInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VersionInfo>
        PARSER = new com.google.protobuf.AbstractParser<VersionInfo>() {
      public VersionInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new VersionInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<VersionInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VersionInfo> getParserForType() {
      return PARSER;
    }

    public grpc.client.Version.VersionInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_client_VersionInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_client_VersionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rversion.proto\022\013grpc.client\"Y\n\013VersionI" +
      "nfo\022\016\n\006number\030\001 \001(\t\022\017\n\007channel\030\002 \001(\t\022\021\n\t" +
      "osVersion\030\003 \001(\t\022\026\n\016androidVersion\030\004 \001(\tb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_grpc_client_VersionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_client_VersionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_client_VersionInfo_descriptor,
        new java.lang.String[] { "Number", "Channel", "OsVersion", "AndroidVersion", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
