// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: authUserAccelStatusResult.proto

package data.data_trans;

@SuppressWarnings("unused")
public final class AuthUserAccelStatusResultOuterClass {
  private AuthUserAccelStatusResultOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AuthUserAccelStatusResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.data_trans.AuthUserAccelStatusResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string shortId = 1;</code>
     */
    String getShortId();
    /**
     * <code>optional string shortId = 1;</code>
     */
    com.google.protobuf.ByteString
        getShortIdBytes();

    /**
     * <code>optional int32 status = 2;</code>
     */
    int getStatus();

    /**
     * <code>optional string expiredTime = 3;</code>
     */
    String getExpiredTime();
    /**
     * <code>optional string expiredTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getExpiredTimeBytes();

    /**
     * <code>optional bool result = 4;</code>
     */
    boolean getResult();

    /**
     * <code>optional int32 code = 5;</code>
     */
    int getCode();
  }
  /**
   * Protobuf type {@code data.data_trans.AuthUserAccelStatusResult}
   */
  public  static final class AuthUserAccelStatusResult extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.data_trans.AuthUserAccelStatusResult)
      AuthUserAccelStatusResultOrBuilder {
    // Use AuthUserAccelStatusResult.newBuilder() to construct.
    private AuthUserAccelStatusResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AuthUserAccelStatusResult() {
      shortId_ = "";
      status_ = 0;
      expiredTime_ = "";
      result_ = false;
      code_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AuthUserAccelStatusResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              shortId_ = s;
              break;
            }
            case 16: {

              status_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              expiredTime_ = s;
              break;
            }
            case 32: {

              result_ = input.readBool();
              break;
            }
            case 40: {

              code_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AuthUserAccelStatusResultOuterClass.internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AuthUserAccelStatusResultOuterClass.internal_static_data_data_trans_AuthUserAccelStatusResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AuthUserAccelStatusResult.class, Builder.class);
    }

    public static final int SHORTID_FIELD_NUMBER = 1;
    private volatile Object shortId_;
    /**
     * <code>optional string shortId = 1;</code>
     */
    public String getShortId() {
      Object ref = shortId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        shortId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string shortId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getShortIdBytes() {
      Object ref = shortId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        shortId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    private int status_;
    /**
     * <code>optional int32 status = 2;</code>
     */
    public int getStatus() {
      return status_;
    }

    public static final int EXPIREDTIME_FIELD_NUMBER = 3;
    private volatile Object expiredTime_;
    /**
     * <code>optional string expiredTime = 3;</code>
     */
    public String getExpiredTime() {
      Object ref = expiredTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        expiredTime_ = s;
        return s;
      }
    }
    /**
     * <code>optional string expiredTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getExpiredTimeBytes() {
      Object ref = expiredTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        expiredTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private boolean result_;
    /**
     * <code>optional bool result = 4;</code>
     */
    public boolean getResult() {
      return result_;
    }

    public static final int CODE_FIELD_NUMBER = 5;
    private int code_;
    /**
     * <code>optional int32 code = 5;</code>
     */
    public int getCode() {
      return code_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getShortIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, shortId_);
      }
      if (status_ != 0) {
        output.writeInt32(2, status_);
      }
      if (!getExpiredTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, expiredTime_);
      }
      if (result_ != false) {
        output.writeBool(4, result_);
      }
      if (code_ != 0) {
        output.writeInt32(5, code_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getShortIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, shortId_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, status_);
      }
      if (!getExpiredTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, expiredTime_);
      }
      if (result_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, result_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, code_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static AuthUserAccelStatusResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AuthUserAccelStatusResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AuthUserAccelStatusResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AuthUserAccelStatusResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AuthUserAccelStatusResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AuthUserAccelStatusResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static AuthUserAccelStatusResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static AuthUserAccelStatusResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static AuthUserAccelStatusResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static AuthUserAccelStatusResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AuthUserAccelStatusResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.data_trans.AuthUserAccelStatusResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.data_trans.AuthUserAccelStatusResult)
        AuthUserAccelStatusResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AuthUserAccelStatusResultOuterClass.internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AuthUserAccelStatusResultOuterClass.internal_static_data_data_trans_AuthUserAccelStatusResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AuthUserAccelStatusResult.class, Builder.class);
      }

      // Construct using data.data_trans.AuthUserAccelStatusResultOuterClass.AuthUserAccelStatusResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        shortId_ = "";

        status_ = 0;

        expiredTime_ = "";

        result_ = false;

        code_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AuthUserAccelStatusResultOuterClass.internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor;
      }

      public AuthUserAccelStatusResult getDefaultInstanceForType() {
        return AuthUserAccelStatusResult.getDefaultInstance();
      }

      public AuthUserAccelStatusResult build() {
        AuthUserAccelStatusResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public AuthUserAccelStatusResult buildPartial() {
        AuthUserAccelStatusResult result = new AuthUserAccelStatusResult(this);
        result.shortId_ = shortId_;
        result.status_ = status_;
        result.expiredTime_ = expiredTime_;
        result.result_ = result_;
        result.code_ = code_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AuthUserAccelStatusResult) {
          return mergeFrom((AuthUserAccelStatusResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AuthUserAccelStatusResult other) {
        if (other == AuthUserAccelStatusResult.getDefaultInstance()) return this;
        if (!other.getShortId().isEmpty()) {
          shortId_ = other.shortId_;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        if (!other.getExpiredTime().isEmpty()) {
          expiredTime_ = other.expiredTime_;
          onChanged();
        }
        if (other.getResult() != false) {
          setResult(other.getResult());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        AuthUserAccelStatusResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (AuthUserAccelStatusResult) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object shortId_ = "";
      /**
       * <code>optional string shortId = 1;</code>
       */
      public String getShortId() {
        Object ref = shortId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          shortId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string shortId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getShortIdBytes() {
        Object ref = shortId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          shortId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string shortId = 1;</code>
       */
      public Builder setShortId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        shortId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortId = 1;</code>
       */
      public Builder clearShortId() {
        
        shortId_ = getDefaultInstance().getShortId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string shortId = 1;</code>
       */
      public Builder setShortIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        shortId_ = value;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>optional int32 status = 2;</code>
       */
      public int getStatus() {
        return status_;
      }
      /**
       * <code>optional int32 status = 2;</code>
       */
      public Builder setStatus(int value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 status = 2;</code>
       */
      public Builder clearStatus() {
        
        status_ = 0;
        onChanged();
        return this;
      }

      private Object expiredTime_ = "";
      /**
       * <code>optional string expiredTime = 3;</code>
       */
      public String getExpiredTime() {
        Object ref = expiredTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          expiredTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string expiredTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getExpiredTimeBytes() {
        Object ref = expiredTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          expiredTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string expiredTime = 3;</code>
       */
      public Builder setExpiredTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        expiredTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string expiredTime = 3;</code>
       */
      public Builder clearExpiredTime() {
        
        expiredTime_ = getDefaultInstance().getExpiredTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string expiredTime = 3;</code>
       */
      public Builder setExpiredTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        expiredTime_ = value;
        onChanged();
        return this;
      }

      private boolean result_ ;
      /**
       * <code>optional bool result = 4;</code>
       */
      public boolean getResult() {
        return result_;
      }
      /**
       * <code>optional bool result = 4;</code>
       */
      public Builder setResult(boolean value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool result = 4;</code>
       */
      public Builder clearResult() {
        
        result_ = false;
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 5;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 5;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:data.data_trans.AuthUserAccelStatusResult)
    }

    // @@protoc_insertion_point(class_scope:data.data_trans.AuthUserAccelStatusResult)
    private static final AuthUserAccelStatusResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AuthUserAccelStatusResult();
    }

    public static AuthUserAccelStatusResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AuthUserAccelStatusResult>
        PARSER = new com.google.protobuf.AbstractParser<AuthUserAccelStatusResult>() {
      public AuthUserAccelStatusResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AuthUserAccelStatusResult(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AuthUserAccelStatusResult> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<AuthUserAccelStatusResult> getParserForType() {
      return PARSER;
    }

    public AuthUserAccelStatusResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_data_trans_AuthUserAccelStatusResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\037authUserAccelStatusResult.proto\022\017data." +
      "data_trans\"o\n\031AuthUserAccelStatusResult\022" +
      "\017\n\007shortId\030\001 \001(\t\022\016\n\006status\030\002 \001(\005\022\023\n\013expi" +
      "redTime\030\003 \001(\t\022\016\n\006result\030\004 \001(\010\022\014\n\004code\030\005 " +
      "\001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_data_trans_AuthUserAccelStatusResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_data_trans_AuthUserAccelStatusResult_descriptor,
        new String[] { "ShortId", "Status", "ExpiredTime", "Result", "Code", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
