// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nodeDetectInfo.proto

package data.data_trans;

@SuppressWarnings("unused")
public final class NodeDetectInfoOuterClass {
  private NodeDetectInfoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface NodeDetectInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.data_trans.NodeDetectInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 code = 1;</code>
     */
    int getCode();

    /**
     * <code>optional int32 uid = 2;</code>
     */
    int getUid();

    /**
     * <code>optional bool succeed = 3;</code>
     */
    boolean getSucceed();
  }
  /**
   * Protobuf type {@code data.data_trans.NodeDetectInfo}
   */
  public  static final class NodeDetectInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.data_trans.NodeDetectInfo)
      NodeDetectInfoOrBuilder {
    // Use NodeDetectInfo.newBuilder() to construct.
    private NodeDetectInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private NodeDetectInfo() {
      code_ = 0;
      uid_ = 0;
      succeed_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private NodeDetectInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 16: {

              uid_ = input.readInt32();
              break;
            }
            case 24: {

              succeed_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.data_trans.NodeDetectInfoOuterClass.internal_static_data_data_trans_NodeDetectInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.data_trans.NodeDetectInfoOuterClass.internal_static_data_data_trans_NodeDetectInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.class, data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>optional int32 code = 1;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int UID_FIELD_NUMBER = 2;
    private int uid_;
    /**
     * <code>optional int32 uid = 2;</code>
     */
    public int getUid() {
      return uid_;
    }

    public static final int SUCCEED_FIELD_NUMBER = 3;
    private boolean succeed_;
    /**
     * <code>optional bool succeed = 3;</code>
     */
    public boolean getSucceed() {
      return succeed_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (uid_ != 0) {
        output.writeInt32(2, uid_);
      }
      if (succeed_ != false) {
        output.writeBool(3, succeed_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, uid_);
      }
      if (succeed_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, succeed_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.data_trans.NodeDetectInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.data_trans.NodeDetectInfo)
        data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.data_trans.NodeDetectInfoOuterClass.internal_static_data_data_trans_NodeDetectInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.data_trans.NodeDetectInfoOuterClass.internal_static_data_data_trans_NodeDetectInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.class, data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.Builder.class);
      }

      // Construct using data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        code_ = 0;

        uid_ = 0;

        succeed_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.data_trans.NodeDetectInfoOuterClass.internal_static_data_data_trans_NodeDetectInfo_descriptor;
      }

      public data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo getDefaultInstanceForType() {
        return data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.getDefaultInstance();
      }

      public data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo build() {
        data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo buildPartial() {
        data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo result = new data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo(this);
        result.code_ = code_;
        result.uid_ = uid_;
        result.succeed_ = succeed_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo) {
          return mergeFrom((data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo other) {
        if (other == data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getSucceed() != false) {
          setSucceed(other.getSucceed());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>optional int32 code = 1;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public int getUid() {
        return uid_;
      }
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public Builder setUid(int value) {
        
        uid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 uid = 2;</code>
       */
      public Builder clearUid() {
        
        uid_ = 0;
        onChanged();
        return this;
      }

      private boolean succeed_ ;
      /**
       * <code>optional bool succeed = 3;</code>
       */
      public boolean getSucceed() {
        return succeed_;
      }
      /**
       * <code>optional bool succeed = 3;</code>
       */
      public Builder setSucceed(boolean value) {
        
        succeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool succeed = 3;</code>
       */
      public Builder clearSucceed() {
        
        succeed_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:data.data_trans.NodeDetectInfo)
    }

    // @@protoc_insertion_point(class_scope:data.data_trans.NodeDetectInfo)
    private static final data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo();
    }

    public static data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NodeDetectInfo>
        PARSER = new com.google.protobuf.AbstractParser<NodeDetectInfo>() {
      public NodeDetectInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new NodeDetectInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<NodeDetectInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NodeDetectInfo> getParserForType() {
      return PARSER;
    }

    public data.data_trans.NodeDetectInfoOuterClass.NodeDetectInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_data_trans_NodeDetectInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_data_trans_NodeDetectInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024nodeDetectInfo.proto\022\017data.data_trans\"" +
      "<\n\016NodeDetectInfo\022\014\n\004code\030\001 \001(\005\022\013\n\003uid\030\002" +
      " \001(\005\022\017\n\007succeed\030\003 \001(\010b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_data_trans_NodeDetectInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_data_trans_NodeDetectInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_data_trans_NodeDetectInfo_descriptor,
        new java.lang.String[] { "Code", "Uid", "Succeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
