// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transData.proto

package data.data_trans;

@SuppressWarnings("unused")
public final class TransDataOuterClass {
  private TransDataOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:data.data_trans.TransData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 method = 1;</code>
     */
    int getMethod();

    /**
     * <code>optional int32 intValue = 2;</code>
     */
    int getIntValue();

    /**
     * <code>optional int64 longValue = 3;</code>
     */
    long getLongValue();

    /**
     * <code>optional string strValue = 4;</code>
     */
    java.lang.String getStrValue();
    /**
     * <code>optional string strValue = 4;</code>
     */
    com.google.protobuf.ByteString
        getStrValueBytes();

    /**
     * <code>optional bool boolValue = 5;</code>
     */
    boolean getBoolValue();

    /**
     * <code>optional bytes data = 6;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code data.data_trans.TransData}
   */
  public  static final class TransData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:data.data_trans.TransData)
      TransDataOrBuilder {
    // Use TransData.newBuilder() to construct.
    private TransData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TransData() {
      method_ = 0;
      intValue_ = 0;
      longValue_ = 0L;
      strValue_ = "";
      boolValue_ = false;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private TransData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              method_ = input.readInt32();
              break;
            }
            case 16: {

              intValue_ = input.readInt32();
              break;
            }
            case 24: {

              longValue_ = input.readInt64();
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              strValue_ = s;
              break;
            }
            case 40: {

              boolValue_ = input.readBool();
              break;
            }
            case 50: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return data.data_trans.TransDataOuterClass.internal_static_data_data_trans_TransData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return data.data_trans.TransDataOuterClass.internal_static_data_data_trans_TransData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              data.data_trans.TransDataOuterClass.TransData.class, data.data_trans.TransDataOuterClass.TransData.Builder.class);
    }

    public static final int METHOD_FIELD_NUMBER = 1;
    private int method_;
    /**
     * <code>optional int32 method = 1;</code>
     */
    public int getMethod() {
      return method_;
    }

    public static final int INTVALUE_FIELD_NUMBER = 2;
    private int intValue_;
    /**
     * <code>optional int32 intValue = 2;</code>
     */
    public int getIntValue() {
      return intValue_;
    }

    public static final int LONGVALUE_FIELD_NUMBER = 3;
    private long longValue_;
    /**
     * <code>optional int64 longValue = 3;</code>
     */
    public long getLongValue() {
      return longValue_;
    }

    public static final int STRVALUE_FIELD_NUMBER = 4;
    private volatile java.lang.Object strValue_;
    /**
     * <code>optional string strValue = 4;</code>
     */
    public java.lang.String getStrValue() {
      java.lang.Object ref = strValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        strValue_ = s;
        return s;
      }
    }
    /**
     * <code>optional string strValue = 4;</code>
     */
    public com.google.protobuf.ByteString
        getStrValueBytes() {
      java.lang.Object ref = strValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        strValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOLVALUE_FIELD_NUMBER = 5;
    private boolean boolValue_;
    /**
     * <code>optional bool boolValue = 5;</code>
     */
    public boolean getBoolValue() {
      return boolValue_;
    }

    public static final int DATA_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 6;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (method_ != 0) {
        output.writeInt32(1, method_);
      }
      if (intValue_ != 0) {
        output.writeInt32(2, intValue_);
      }
      if (longValue_ != 0L) {
        output.writeInt64(3, longValue_);
      }
      if (!getStrValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, strValue_);
      }
      if (boolValue_ != false) {
        output.writeBool(5, boolValue_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(6, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (method_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, method_);
      }
      if (intValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, intValue_);
      }
      if (longValue_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, longValue_);
      }
      if (!getStrValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, strValue_);
      }
      if (boolValue_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boolValue_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static data.data_trans.TransDataOuterClass.TransData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(data.data_trans.TransDataOuterClass.TransData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code data.data_trans.TransData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:data.data_trans.TransData)
        data.data_trans.TransDataOuterClass.TransDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return data.data_trans.TransDataOuterClass.internal_static_data_data_trans_TransData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return data.data_trans.TransDataOuterClass.internal_static_data_data_trans_TransData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                data.data_trans.TransDataOuterClass.TransData.class, data.data_trans.TransDataOuterClass.TransData.Builder.class);
      }

      // Construct using data.data_trans.TransDataOuterClass.TransData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        method_ = 0;

        intValue_ = 0;

        longValue_ = 0L;

        strValue_ = "";

        boolValue_ = false;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return data.data_trans.TransDataOuterClass.internal_static_data_data_trans_TransData_descriptor;
      }

      public data.data_trans.TransDataOuterClass.TransData getDefaultInstanceForType() {
        return data.data_trans.TransDataOuterClass.TransData.getDefaultInstance();
      }

      public data.data_trans.TransDataOuterClass.TransData build() {
        data.data_trans.TransDataOuterClass.TransData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public data.data_trans.TransDataOuterClass.TransData buildPartial() {
        data.data_trans.TransDataOuterClass.TransData result = new data.data_trans.TransDataOuterClass.TransData(this);
        result.method_ = method_;
        result.intValue_ = intValue_;
        result.longValue_ = longValue_;
        result.strValue_ = strValue_;
        result.boolValue_ = boolValue_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof data.data_trans.TransDataOuterClass.TransData) {
          return mergeFrom((data.data_trans.TransDataOuterClass.TransData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(data.data_trans.TransDataOuterClass.TransData other) {
        if (other == data.data_trans.TransDataOuterClass.TransData.getDefaultInstance()) return this;
        if (other.getMethod() != 0) {
          setMethod(other.getMethod());
        }
        if (other.getIntValue() != 0) {
          setIntValue(other.getIntValue());
        }
        if (other.getLongValue() != 0L) {
          setLongValue(other.getLongValue());
        }
        if (!other.getStrValue().isEmpty()) {
          strValue_ = other.strValue_;
          onChanged();
        }
        if (other.getBoolValue() != false) {
          setBoolValue(other.getBoolValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        data.data_trans.TransDataOuterClass.TransData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (data.data_trans.TransDataOuterClass.TransData) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int method_ ;
      /**
       * <code>optional int32 method = 1;</code>
       */
      public int getMethod() {
        return method_;
      }
      /**
       * <code>optional int32 method = 1;</code>
       */
      public Builder setMethod(int value) {
        
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 method = 1;</code>
       */
      public Builder clearMethod() {
        
        method_ = 0;
        onChanged();
        return this;
      }

      private int intValue_ ;
      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public int getIntValue() {
        return intValue_;
      }
      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public Builder setIntValue(int value) {
        
        intValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 intValue = 2;</code>
       */
      public Builder clearIntValue() {
        
        intValue_ = 0;
        onChanged();
        return this;
      }

      private long longValue_ ;
      /**
       * <code>optional int64 longValue = 3;</code>
       */
      public long getLongValue() {
        return longValue_;
      }
      /**
       * <code>optional int64 longValue = 3;</code>
       */
      public Builder setLongValue(long value) {
        
        longValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 longValue = 3;</code>
       */
      public Builder clearLongValue() {
        
        longValue_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object strValue_ = "";
      /**
       * <code>optional string strValue = 4;</code>
       */
      public java.lang.String getStrValue() {
        java.lang.Object ref = strValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          strValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string strValue = 4;</code>
       */
      public com.google.protobuf.ByteString
          getStrValueBytes() {
        java.lang.Object ref = strValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          strValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string strValue = 4;</code>
       */
      public Builder setStrValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        strValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string strValue = 4;</code>
       */
      public Builder clearStrValue() {
        
        strValue_ = getDefaultInstance().getStrValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string strValue = 4;</code>
       */
      public Builder setStrValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        strValue_ = value;
        onChanged();
        return this;
      }

      private boolean boolValue_ ;
      /**
       * <code>optional bool boolValue = 5;</code>
       */
      public boolean getBoolValue() {
        return boolValue_;
      }
      /**
       * <code>optional bool boolValue = 5;</code>
       */
      public Builder setBoolValue(boolean value) {
        
        boolValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolValue = 5;</code>
       */
      public Builder clearBoolValue() {
        
        boolValue_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 6;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 6;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:data.data_trans.TransData)
    }

    // @@protoc_insertion_point(class_scope:data.data_trans.TransData)
    private static final data.data_trans.TransDataOuterClass.TransData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new data.data_trans.TransDataOuterClass.TransData();
    }

    public static data.data_trans.TransDataOuterClass.TransData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransData>
        PARSER = new com.google.protobuf.AbstractParser<TransData>() {
      public TransData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new TransData(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<TransData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransData> getParserForType() {
      return PARSER;
    }

    public data.data_trans.TransDataOuterClass.TransData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_data_data_trans_TransData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_data_data_trans_TransData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017transData.proto\022\017data.data_trans\"s\n\tTr" +
      "ansData\022\016\n\006method\030\001 \001(\005\022\020\n\010intValue\030\002 \001(" +
      "\005\022\021\n\tlongValue\030\003 \001(\003\022\020\n\010strValue\030\004 \001(\t\022\021" +
      "\n\tboolValue\030\005 \001(\010\022\014\n\004data\030\006 \001(\014b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_data_data_trans_TransData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_data_data_trans_TransData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_data_data_trans_TransData_descriptor,
        new java.lang.String[] { "Method", "IntValue", "LongValue", "StrValue", "BoolValue", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
